### ISSUE TITLE
custom folder

### ISSUE THREAD

**Issue by citovsky** [IngmarStein/Monolingual#1]
is it possible to allow monolingual to reside in a custom folder (not in Applications) and still not to have to input password twice? thanks

**Comment by IngmarStein** [comment]
Is this still the case with 1.6.7?

**Comment by citovsky** [comment]
all is ok now, thank u so much but it still requires two inputs of password when run from a custom folder


--------------------------
Vitaly Citovsky
Department of Biochemistry and Cell Biology
State University of New York
Stony Brook, NY 11794-5215
Tel.: 631.632.9534
Fax: 631.632.8575
E-mail: vitaly.citovsky@stonybrook.edu
😄

**Comment by IngmarStein** [comment]
Ok, I'll try to fix that password prompt. You could help me by providing the console output again (you can leave out all those "Blacklisting…" lines). Here's how it should look:

First time:
05.04.15 15:40:27,310 Monolingual[92636]: net.sourceforge.MonolingualHelper (1.6.7) installed successfully

Subsequent launches:
05.04.15 15:41:22,406 Monolingual[92665]: net.sourceforge.MonolingualHelper (1.6.7) is already current, skipping install.

**Comment by citovsky** [comment]
ok, thanks. i’ll send the file to u tomorrow. traveling today. where is it again? in which directory?


------------------------------
Dr. Vitaly Citovsky
SUNY Distinguished Professor
Department of Biochemistry and Cell Biology
State University of New York
Stony Brook, NY 11794-5215
Tel.: 631.632.9534
Fax: 631.632.8575
E-mail: vitaly.citovsky@stonybrook.edu

**Comment by IngmarStein** [comment]
/Applications/Utilities/Console.app

**Comment by citovsky** [comment]
thanks


--------------------------
Vitaly Citovsky
Department of Biochemistry and Cell Biology
State University of New York
Stony Brook, NY 11794-5215
Tel.: 631.632.9534
Fax: 631.632.8575
E-mail: vitaly.citovsky@stonybrook.edu
😄

**Comment by citovsky** [comment]
i meant the directory for the log file to be opened by console. i’ll just send it to u


--------------------------
Vitaly Citovsky
Department of Biochemistry and Cell Biology
State University of New York
Stony Brook, NY 11794-5215
Tel.: 631.632.9534
Fax: 631.632.8575
E-mail: vitaly.citovsky@stonybrook.edu
😄

**Comment by IngmarStein** [comment]
/var/log/system.log

**Comment by citovsky** [comment]
thanks


--------------------------
Vitaly Citovsky
Department of Biochemistry and Cell Biology
State University of New York
Stony Brook, NY 11794-5215
Tel.: 631.632.9534
Fax: 631.632.8575
E-mail: vitaly.citovsky@stonybrook.edu
😄

**Comment by citovsky** [comment]
here it is but now this version does not require password. i think it is perfect now!!!!


--------------------------
Vitaly Citovsky
Department of Biochemistry and Cell Biology
State University of New York
Stony Brook, NY 11794-5215
Tel.: 631.632.9534
Fax: 631.632.8575
E-mail: vitaly.citovsky@stonybrook.edu
😄
