### ISSUE TITLE
Dictionaries ?

### ISSUE THREAD

**Issue by DG12** [IngmarStein/Monolingual#100]
Any plans to delete /Library/Dictionaries ?

Thank you

**Comment by IngmarStein** [comment]
Monolingual's main purpose is to find all the localization files scattered across the file system and be clever about which ones to delete and which ones to keep (e.g. not to invalidate code signatures). Dictionaries are stored in a well-defined location and can easily be deleted by hand, if needed.

If you want a more extensive application which serves as a dashboard for all kinds of files you might want to remove, I recommend CleanMyMac.

**Comment by DG12** [comment]
Multi-lingual Dictionaries are in a well defined location (If you know they even exist).

Many of us are really afraid of CleanMyMac and CleanMyPC (but trust you much more!)

**Comment by IngmarStein** [comment]
Thanks!

From time to time, I get feature requests such as this one of #89 which would increase the effort required to maintain Monolingual. I try to keep this tool as simple and focused as possible. The functionality to thin multi-architecture executables is an exception as it was most valuable during the PowerPC/Intel transition, but it's of little use right now. I only keep it in case macOS moves to ARM at some point.

If someone goes ahead and submits a pull request, I'm happy to merge it!
