### ISSUE TITLE
Stuck User boot screen on sierra - macbook

### ISSUE THREAD

**Issue by B4RK1N** [IngmarStein/Monolingual#104]
Anyone help me, please.

**Comment by IngmarStein** [comment]
What makes you think this is related to Monolingual? What operation did you perform?

**Comment by B4RK1N** [comment]
Hello Master,

Thx so much for ur help.

Respectively, i did;

install Monolingual
Remove languages tab
Remove architectures tab
Restart macbook

stuck user account login screen after enter my password

**Comment by B4RK1N** [comment]
And always same screen (attach photo)
![img_0888](https://cloud.githubusercontent.com/assets/25352120/22308459/b3ea302a-e34f-11e6-9448-03758475d31b.JPG)
, try  more restart.

**Comment by B4RK1N** [comment]
Mr.IngmarStein,

If is it possible reboot system? I need ur help.
Because i have important files that are not backed up.

**Comment by IngmarStein** [comment]
Yes, you can reboot the machine by holding the power button (https://support.apple.com/en-us/HT201150). Then hold ⌘R to reinstall macOS (https://support.apple.com/en-us/HT201314) which preserves your data.

**Comment by B4RK1N** [comment]
Ok, thanks so much.
