### ISSUE TITLE
Monolingual 1.7.6. is broken several apps...

### ISSUE THREAD

**Issue by readingsnail** [IngmarStein/Monolingual#108]
<img width="541" alt="2017-02-09 8 32 53" src="https://cloud.githubusercontent.com/assets/1904967/22762405/7cd8bfee-eea2-11e6-98cf-066a5a291fcc.png">

i try this option, and after monolingual action, several apps is not working (yeah, i not deleted Intel Architecture but many apps is broken)... i don't know what's happen. sorry for not log file :'( i forgot this...

**Comment by IngmarStein** [comment]
Which apps are broken? Can you provide a crashlog?

**Comment by Jaanuseonu** [comment]
I have same problem with 1.7.6 and OS Sierra 10.12.3. System preferences and Photos app are broken after architecture cleaning.

**Comment by readingsnail** [comment]
@IngmarStein sorry for no log, because it's almost break out, so rast resort, i going to internet recovery & older timemachine backup is removing...

anyway, dropbox, air video hd etc... almost 50%+ app is broken. (yeah, not working icon)

**Comment by IngmarStein** [comment]
I might have found the issue. 1.7.6 added support for the 64-bit fat file format and due to a typo a wrong magic number was written. I'll wait for a crashlog to verify if that was the issue.

**Comment by readingsnail** [comment]
[ibooks crash.txt](https://github.com/IngmarStein/Monolingual/files/763310/ibooks.crash.txt)
<img width="1280" alt="2017-02-09 7 12 00" src="https://cloud.githubusercontent.com/assets/1904967/22779030/78112e24-eefc-11e6-89e2-3a9439415589.png">
[photos crashreport.txt](https://github.com/IngmarStein/Monolingual/files/763311/photos.crashreport.txt)
[bkagent crash.txt](https://github.com/IngmarStein/Monolingual/files/763312/bkagent.crash.txt)

firefox broken, so upload several apple app's crash report.

**Comment by IngmarStein** [comment]
I could reproduce the problem and the commit above fixed it. If you had also selected "Intel 32", the resulting files would have been thin (i.e. non-fat) binaries, not exhibiting the isse.

I'll publish a new build release. Sorry for the trouble!

**Comment by readingsnail** [comment]
i not check 'intel 32', but monolingual maybe check 'intel 32', so this problem

**Comment by IngmarStein** [comment]
In the screenshot above, "Intel 32-bit" wasn't checked. The bug would not have manifested itself if you had checked it. Anyways, 1.7.7 is out in a few minutes.

**Comment by IngmarStein** [comment]
Please let me know if this is fixed now.

**Comment by readingsnail** [comment]
in 1.7.7, bug fixed. thanks :) all app is well working now :)
