### ISSUE TITLE
Monolingual 1.7.7 Architecture removal bug

### ISSUE THREAD

**Issue by Jaanuseonu** [IngmarStein/Monolingual#109]
Sorry for my bad English.

I checked disk used space before i start Architecture cleaning, it shows 65.93GB.
Monolingual start cleaning and during cleaning time disk free space decreased.
Monolingual finished and it shows that space saved 1.55GB. I checked again disk used space, then it shows 66.02GB.
I start again Architecture cleaning, Monolingual finished and it shows again space saved 1.55GB. Now disk used space is has increased even more - 66.08GB

Where can I find Monolingual log file?

**Comment by IngmarStein** [comment]
The log file can be found at `~/Library/Logs/Monolingual.log`.

**Comment by IngmarStein** [comment]
This might be due to SIP (system integrity protection): Monolingual is able to create the output file but SIP prevents it from replacing the original. Monolingual then wrongly reports this as successful. I'll patch this in the next version.

**Comment by IngmarStein** [comment]
Could you please verify if this is fixed for you in 1.7.8?
