### ISSUE TITLE
does not remove zh-Hans.lproj and zh-Hant.lproj

### ISSUE THREAD

**Issue by citovsky** [IngmarStein/Monolingual#117]
does not remove zh-Hans.lproj and zh-Hant.lproj. please fix

**Comment by IngmarStein** [comment]
Which files do you expect to be removed? Could you please a produce a list of absolute paths?
Is SIP enabled on your machine or not?

**Comment by citovsky** [comment]
thank you for the quick reply. SIP is disabled

i only want to be able to remove zh-Hans.lproj and zh-Hant.lproj folders from the resources. these are chinese language i think. i do not know about a list of absolute paths,but they r located as i said in the resources folder


------------------------------
Dr. Vitaly Citovsky
SUNY Distinguished Professor
Department of Biochemistry and Cell Biology
State University of New York
Stony Brook, NY 11794-5215
Tel.: 631.632.9534
Fax: 631.632.8575
E-mail: vitaly.citovsky@stonybrook.edu

**Comment by IngmarStein** [comment]
The resources directory for which applications? This makes a difference because some applications are blacklisted because they check for the existence of those files (and refuse to work without them) and other applications include them as part of their digital signature and Monolingual pays attention not to invalidate it.

**Comment by citovsky** [comment]
i think it never removes zh-Hans.lproj and zh-Hant.lproj from anywhere. it removes zh_Hans.lproj but not zh-Hans.lproj, for example.

examples of some apps are Skype and 1Password


--------------------------
Vitaly Citovsky
Department of Biochemistry and Cell Biology
State University of New York
Stony Brook, NY 11794-5215
Tel.: 631.632.9534
Fax: 631.632.8575
E-mail: vitaly.citovsky@stonybrook.edu
😄

**Comment by IngmarStein** [comment]
Thanks for your report (again) - I think I've fixed it this time. Will be part of the next version.

**Comment by citovsky** [comment]
thanks!


--------------------------
Vitaly Citovsky
Department of Biochemistry and Cell Biology
State University of New York
Stony Brook, NY 11794-5215
Tel.: 631.632.9534
Fax: 631.632.8575
E-mail: vitaly.citovsky@stonybrook.edu
😄

**Comment by DG12** [comment]
Does Monolingual handle 
Library/Image Capture/Devices/Canon IJScanner4.app/Contents/Resources
there exists a zh-Hant.lproj and  zh-Hans.lproj on my system which are empty!

FYI System/Library/PrivateFrameworks/ACDEClient.framework/Versions/A/Resources/ contains
36 language files which are empty.

Have you mentioned in the docs that "of course" monolingual use be rerun after installing/upgrading apps?

**Comment by citovsky** [comment]
i checked these paths and do not have those language files at all


--------------------------
Vitaly Citovsky
Department of Biochemistry and Cell Biology
State University of New York
Stony Brook, NY 11794-5215
Tel.: 631.632.9534
Fax: 631.632.8575
E-mail: vitaly.citovsky@stonybrook.edu
😄
