### ISSUE TITLE
adding 

### ISSUE THREAD

**Issue by DG12** [IngmarStein/Monolingual#119]
Perhaps adding something like:

Signals.trap(signal: .int ) { signal in
        print(" Monolingual processing file : ... at start+ d seconds   continue ?
       } 

Would be helpful 
Note that  INTerrupt usually ^C ((see stty -a))  and  QUIT usually ^\  

https://github.com/IBM-Swift/BlueSignals

NOT like https://gist.github.com/jakubpetrik/8fe8b1b6c5829d8ca94a !

**Comment by IngmarStein** [comment]
What for? Which signal do you suggest should have a custom handler?

**Comment by DG12** [comment]
Both INTerrupt to display Currently deleting file and QUIT is user thinks monolingual is stuck and wants to terminate.

**Comment by IngmarStein** [comment]
But why? Monolingual has a UI. If the user thinks it is stuck, one can just use Cmd-Q. Do you expect someone to send the process a SIGINT?

**Comment by DG12** [comment]
I tried command C and it is ignored (i.e. Mac beeps).
Cancel should display last/current. directory/file. 
Perhaps after that it could display "sure?" and allow continue.

**Comment by IngmarStein** [comment]
Sorry, I don't get it. Why do you expect Command-C which usually means "copy" to perform a "cancel" operation? Which other Mac app with a UI does what you describe?

**Comment by DG12** [comment]
Sorry I miss read Cmd-Q as Cmd-c

**Comment by IngmarStein** [comment]
Do you have an example of a graphical app that does what you describe above?

**Comment by DG12** [comment]
I cannot think of any apps that have a "pause, what's your status'" button.
However I can't think of any app that run as long as monolingual does(sometimes) without displaying progress (not that stupid thermometer either).
.
I only make this suggestion that it might help you in diagnosing those "monolingual is stuck" issues.

Thanks for providing this utility.
Dennis

**Comment by IngmarStein** [comment]
Thanks for your suggestion, but this is not something useful to a majority of users. A crashlog would help a lot more for fixing #115. Usually, Monolingual should not take more than a few minutes.
