### ISSUE TITLE
NetFSPlugins/ftp.bundle

### ISSUE THREAD

**Issue by DG12** [IngmarStein/Monolingual#122]
Did you want to include:
/System/Library/Filesystems/NetFSPlugins/ftp.bundle/Contents/Resources

**Comment by IngmarStein** [comment]
There's no global include list for Monolingual (just a blacklist for apps which are known to have issues with missing localization files). So, if you add `/System/Library/Filesystems` (for example) in Monolingual's preferences, it will be processed.
