### ISSUE TITLE
What is Monolingual about?

### ISSUE THREAD

**Issue by haltlos** [IngmarStein/Monolingual#125]
Sometimes, being too brief is not being helpful. The description of what Monolognual does is too short and the FAQ don't address very basic questions like the following:

1. Which "language resources" are the subject of this application?
2. What is the consequence of removing a "language"?
3. How to add a removed language back to the operating system?
4. Do "language resources" affect fonts used by applications and PDFs in any way?
5. How will I notice that a language got removed?
6. How are localization files of macOS different from localization files of applications? Do the latter depend on the former?

I hope these questions show that you are nowhere near to giving me the confidence in using Monolingual. Please provide more details, because I don't like to change things before understanding what the consequences are.

**Comment by IngmarStein** [comment]
Monolingual is open for contributions. If you feel that the documentation is not adequate, feel free to open a pull request to improve it.
