### ISSUE TITLE
Trying to find Monolingual Version 1.1.2

### ISSUE THREAD

**Issue by eisnerguy1** [IngmarStein/Monolingual#126]
Didn't know where else to ask this.  Is there any way I can have the dmg for Monolingual Version 1.1.2?  I've been messing around with Mac OS X 10.1.5 in Qemu and I could really use this.

**Comment by eisnerguy1** [comment]
This can be closed.  <a href="http://web.archive.org/web/20041009215545/http://homepage.mac.com:80/jschrier/index.html">I found it</a>

**Comment by IngmarStein** [comment]
Good find ;)

**Comment by eisnerguy1** [comment]
Thanks.  In <a href="https://www.emaculation.com/forum/viewforum.php?f=34&sid=b822934dbaacd6ee2d6ba799eab78469">Qemu</a>, I actually got the OmniGroup ports of Fallout & Fallout 2 running pretty great.
