### ISSUE TITLE
[ 1.7.8 ] Amnesic Monolingual

### ISSUE THREAD

**Issue by cig0** [IngmarStein/Monolingual#127]
Monolingual arbitrary selects the languages and machine architectures to remove based on system specs -- and it does a good damn job there.

However, it should also remember user's preferences for both categories.

**Comment by IngmarStein** [comment]
Hi. Thanks for using Monolingual. Have you checked the FAQ on https://ingmarstein.github.io/Monolingual/faq.html? Entry 3 should answer the language part of your question.
