### ISSUE TITLE
Nothing actually freed according to "Get Info"

### ISSUE THREAD

**Issue by boardhead** [IngmarStein/Monolingual#128]
Ran Monolingual 1.7.8 on MacBook Pro with MacOS 10.13.3.

It reported that it cleaned about 0.5 GB for languages, and almost 1 GB for architectures.

But using File/Get Info on the disk shows exactly the same available and purgeable space on the drive before and afterwards.

When I Monolingual again, it doesn't find anything else to clean.

So my question is, where did those files go, and why don't they show up as extra available space on the hard disk?

I had all of the default preferences set.  (ie. "move to trash" was not selected)

**Comment by IngmarStein** [comment]
Monolingual adds the allocation sizes for all the files it unlinks. For APFS volumes, this does not necessarily lead to the Finder displaying more "free space" afterwards. One reason for that are APFS snapshots. The disk space is only recovered when the last snapshot referencing the files is deleted.

See https://www.jethrocarr.com/2017/11/06/macos-high-sierra-unable-to-free-disk-space/ for some more information.
