### ISSUE TITLE
1.8.0 and zh-Hans.lproj/zh-Hant.lproj removal

### ISSUE THREAD

**Issue by unsureone** [IngmarStein/Monolingual#131]
Now that the 1.8.0 build is passing (after the update to Xcode 9.3), would you consider releasing a new compiled build? The fix to remove zh-Hans.lproj and zh-Hant.lproj resources was committed after the release of 1.7.8, and a compiled build of 1.7.9 wasn't posted, so users still aren't having those resources removed.

I notice that fastlane's current release is at 2.85.0, while the version used in Monolingual is still at 2.77.1.  It'd be nice to have that updated as well, assuming that it doesn't break the build.

Thanks,
David

**Comment by IngmarStein** [comment]
If you're referring to the Travis CI build: the Xcode 9.3 now finally runs on mac OS 10.13. Previously, the tests failed because Monolingual 1.8 requires High Sierra.

I'll try to publish a new release soon.

**Comment by IngmarStein** [comment]
1.8.0 has just been released.

**Comment by unsureone** [comment]
Yes, I was referring to the Travis CI build.
Thank you so much for releasing 1.8.0; I really appreciate your hard work on this project!

Thanks,
David
