### ISSUE TITLE
does not report size removed files

### ISSUE THREAD

**Issue by citovsky** [IngmarStein/Monolingual#132]
although v 1.8 appears to work it always reports only 1 byte of removed files. i run it under MacOs X 10.13.4 developers beta v. 5

**Comment by unsureone** [comment]
I've experienced the same issue with 1.8.0 on 10.13.4 DB5.

On MacUpdate, four people have experienced it with 1.8.0, with one person on 10.13.4 DB5, one on 10.13.3, and two who didn't specify which version of 10.13 they were using.

-- David

**Comment by JKLStudiosInc** [comment]
Same here. 1.7.8 works as expected. Well, technically, so does 1.8. For instance, I can watch a 116 MB app drop to 85 MB as Monolingual is running, but it reports only 1 byte removed.

![screen shot 1](https://user-images.githubusercontent.com/10281201/37538745-9697ad42-291f-11e8-80b2-c0588975896a.png)

Also, while the app is running, it doesn't show anything happening where you would normally see what language files it's removing. The sheet stays blank through the entire process.

![screen shot](https://user-images.githubusercontent.com/10281201/37538799-c35b5c98-291f-11e8-9270-33f6ed232183.png)

This is under 10.3.3.

**Comment by ramuntcho** [comment]
Hello,

Quite the same thing with Monolingual 1.8 on 10.13.3. As always, I remove all languages, except en, en (United States), fr, fr (France) and fr (Switzerland, my system). Normally, I remove 1.7 Go, and now it says that 1 octet was removed. I didn't notice that it has done his work (no reduction of 1.7 Go).
Something strange : if I remember correctly, Monoingual asks for a admin authentification first, but in this case, it asks for nothing, starting his work... and doing nothing.

**Comment by IngmarStein** [comment]
I've filed a radar with Apple (rdar://38600258) which broke progress reporting from the XPC helper to the main app. I'll try to find a workaround or revert to the previous method in the next release. Please note that this only affects reporting (updating the UI with the currently processed files, writing the log file, and presenting the total size), not the actual operation of the app itself.

**Comment by citovsky** [comment]
Thank you!

-----------------
Dr. Vitaly Citovsky
SUNY Distinguished Professor
Department of Biochemistry and Cell Biology
State University of New York
Stony Brook, NY 11794-5215
Tel.: 631.632.9534
E-mail: vitaly.citovsky@stonybrook.edu
😀

**Comment by IngmarStein** [comment]
Should be worked around in 1.8.1.
