### ISSUE TITLE
Mistakenly removed English language and affecting Windows

### ISSUE THREAD

**Issue by ccsuperchris** [IngmarStein/Monolingual#136]
Hello IngmarStein, I'm not in IT at all but came across Monolingual when I was looking for ways to clear up space on my Apple MacBook Air. I ticked to keep English (UK), English (US), English (Australia) and French but unfortunately as per your first FAQ, I removed English in error. Now I am unable to open my Microsoft Office apps - Excel, Word, Powerpoint. I am also unable to open my existing Excel files in Numbers, or Word files in Pages, respectively. The error message that comes up is attached below, the usual application error messages. 
![screen shot 2018-05-05 at 3 06 57 pm](https://user-images.githubusercontent.com/38999151/39660622-657abf9a-5086-11e8-8693-870205bbb2b5.png)
Is there a way of reinstating the "English" language choice? Unfortunately I don't know any coding at all... Thanks, Chris.

**Comment by ccsuperchris** [comment]
@IngmarStein Apologies, I should advise that I downloaded Monolingual 1.8.0 and I'm on Mac OS High Sierra 10.13.4.

**Comment by IngmarStein** [comment]
The solution is to reinstall the apps where the English localizations have been removed accidentally.
