### ISSUE TITLE
New version request

### ISSUE THREAD

**Issue by unsureone** [IngmarStein/Monolingual#140]
Do you think that we might be able to get a new release of Monolingual, now that macOS 10.14 has been released? I've noticed that you're using Xcode 10 now and that it builds fine with Travis. It would also allow users to see the actual space saved, since you resolved that in the code on March 23--after Monolingual 1.8.0 was released.

Many thanks,
David

**Comment by IngmarStein** [comment]
Yes, I think it's about time for another release, but I haven't yet checked if there's a problem traversing a full file system (or just everything in a user's home directory, for that matter) or if that triggers Mojave's new prompts to access photos, calendars and contacts and if I need to add usage descriptions to Info.plist since I've enabled the new hardened runtime.
See https://github.com/atom/atom/issues/17687

**Comment by billearl** [comment]
I concur, and hope you can sort it out.

**Comment by unsureone** [comment]
It's been 47 days since my first request, so I was wondering if there's an ETA for the Mojave version of Monolingual.

**Comment by citovsky** [comment]
it works, u can configure it to move files to trash and will find hundreds of files there after monolingual is done. but the app desperately needs an update with this issue corrected and may be PLEASE an option to run it automatically every several days or so

**Comment by citovsky** [comment]
also it would be nice to make it possible to ignore the active keyboard layouts such the monolingual removes even those languages for which keyboards are active

**Comment by ArminP** [comment]
> it works, u can configure it to move files to trash and will find hundreds of files there after monolingual is done. but the app desperately needs an update with this issue corrected and may be PLEASE an option to run it automatically every several days or so

Thanks for the tip.

**Comment by IngmarStein** [comment]
Could you please give https://github.com/IngmarStein/Monolingual/releases/tag/v1.8.1 a try? I've marked it as a prerelease for now.

**Comment by citovsky** [comment]
Thanks. I will later tonight 

-----------------
Dr. Vitaly Citovsky
SUNY Distinguished Professor
Department of Biochemistry and Cell Biology
State University of New York
Stony Brook, NY 11794-5215
Tel.: 631.632.9534
E-mail: vitaly.citovsky@stonybrook.edu
😀

**Comment by billearl** [comment]
Thanks. It crashed on macOS 10.14.3 Beta (18D21c). Error logs are attached.

[Monolingual 1.8.1 pre-release error logs.zip](https://github.com/IngmarStein/Monolingual/files/2692080/Monolingual.1.8.1.pre-release.error.logs.zip)

**Comment by citovsky** [comment]
So I ran it under 10.14.3 beta 3 18d21c on my 13” 2016 MacBook Pro and it did NOT crash. Everything works fine. Will try tomorrow on my iMac retina under the same OS.

I still would like to have 2 enhancements: 

1. Option to run automatically every once a while, like once a day or a week.
2. Option to NOT deselect languages that are in the active keyboard layouts. For example, I have a Hebrew layout active but I do not need Hebrew localization. So I go every time and select this option. Kind of annoying

Thanks 


--------------------------
Vitaly Citovsky
Department of Biochemistry and Cell Biology
State University of New York
Stony Brook, NY 11794-5215
Tel.: 631.632.9534
E-mail: vitaly.citovsky@stonybrook.edu
😄

**Comment by citovsky** [comment]
tried it on an iMac under 10.14.3 18D21c and it works fine. so on both MacBook pro Touch Bar and iMac it works fine under the latest developers beta of mac os

thanks


--------------------------
Vitaly Citovsky
Department of Biochemistry and Cell Biology
State University of New York
Stony Brook, NY 11794-5215
Tel.: 631.632.9534
E-mail: vitaly.citovsky@stonybrook.edu
😄

**Comment by IngmarStein** [comment]
Thanks for testing, I released 1.8.1. Please create new issues for other topics (like looking at keyboard layouts to determine the initial list of languages to be removed).
