### ISSUE TITLE
option not to look at keyboard layouts to determine the initial list of languages to be removed

### ISSUE THREAD

**Issue by citovsky** [IngmarStein/Monolingual#150]
please add an option not to look at keyboard layouts to determine the initial list of languages to be removed. thanks

**Comment by IngmarStein** [comment]
Monolingual does in fact not care about keyboard layouts. It only looks at the "preferred languages" listed in the Language & Region pane in System Preferences.

**Comment by citovsky** [comment]
Thanks 


--------------------------
Vitaly Citovsky
Department of Biochemistry and Cell Biology
State University of New York
Stony Brook, NY 11794-5215
Tel.: 631.632.9534
E-mail: vitaly.citovsky@stonybrook.edu
😄
