### ISSUE TITLE
Monolingual 1.8.1 reporting issues

### ISSUE THREAD

**Issue by billearl** [IngmarStein/Monolingual#151]
First, Monolingual's progress bar goes immediately to 100% with only a static "Removing..." message, not very entertaining.

Second, when completed, it reports space saved is 52.21 TB, which is a bit more than my 1.5 TB boot partition will hold.

**Comment by rogershieh** [comment]
Can confirm both on High Sierra, I got _321.41 PB_ from my 120GB partition

**Comment by jituv** [comment]
I can confirm here too on Mojave. Now the real question, is there any ETA on an update? :)

**Comment by billearl** [comment]
I suspect Ingmar is busy with other work, or has lost interest in Monolingual. Not so responsive for the last while anyway.

I miss the older version (1.78?) that seemed to work as it should. I'd be willing to pay for Monolingual if he committed to support it better.

**Comment by billearl** [comment]
Thanks, Ingmar. I'm grateful to you for Monolingual and didn't intend to criticize your efforts. What you describe is about what I understood to be the case. Unfortunately, I can't contribute on the coding side. The Monolingual 1.8.1 deficiencies are trivial to it's functionality.

**Comment by JKLStudiosInc** [comment]
Just to confirm a bit more on the size reporting. It is trivial to those who understand it couldn't have removed that much data, but the size is reported in powers of 2 above what was actually removed.

If Monolingual removes Megabytes, it reports Terabytes. If Gigabytes, it reports Exabytes.

I still much prefer this misreported size to zero. :-)

**Comment by IngmarStein** [comment]
I've uploaded a pre-release of 1.8.2, if you want to give it a try.

**Comment by billearl** [comment]
Thanks, Ingmar. I just ran Monolingual 1.8.2, and it reported 78.6 MB, which looks realistic. It also displayed the names of various apps it was removing language resources from. Unfortunately, I thought too late to have it move language resources to the trash, so I could confirm the actual size of those resources. However, it looks fixed to me, so I'm happy.

**Comment by IngmarStein** [comment]
Thanks for testing @billearl!
