### ISSUE TITLE
.lproj files in /Applications/Numbers.app/Contents/SharedSupport/Templates/

### ISSUE THREAD

**Issue by ECTim** [IngmarStein/Monolingual#154]
Used Terminal csrutil disable and then successfully continued to use Monolingual to purge a lot of .lproj files in Apple programs. Closer scrutiny shows Numbers/Pages/Keynote left untouched many files in their respective Templates folder, e.g. in /Applications/Numbers.app/Contents/SharedSupport/Templates/

Any idea how I can clean them out other than manually?

**Comment by IngmarStein** [comment]
Those files are part of the code signatures of the respective applications. For example, `<key>SharedSupport/Templates/00_BasicCategories/ar.lproj/Localizable.strings</key>` is listed in `/Applications/Numbers.app/Contents/_CodeSignature/CodeResources`. That means, removing them would break the signatures. Monolingual takes extra care to not break those, even when SIP is disabled.

**Comment by ECTim** [comment]
Thanks for prompt reply.

I had deleted .lproj files from the Templates directory so was now concerned that I had damaged the app in some way. 
Using Terminal all appears ok:
codesign --verify --verbose /Applications/Pages.app
/Applications/Pages.app: valid on disk
/Applications/Pages.app: satisfies its Designated Requirement

**Comment by IngmarStein** [comment]
If you only deleted files that have `<key>optional</key><true/>` (like `/Applications/Numbers.app/Contents/Resources/FunctionHelp.bundle/Contents/Resources/ar.lproj/Art/Functions_Help.png`, for example), you should be fine. Those are optional parts of the code signature, i.e. it's considered ok if they're missing. Monolingual should delete those.
Try `codesign --verify --verbose --deep /Applications/Pages.app` to verify the signature recursively to be sure.

**Comment by ECTim** [comment]
codesign --verify --verbose --deep /Applications/Numbers.app
codesign --verify --verbose --deep /Applications/Numbers.app
/Applications/Numbers.app: a sealed resource is missing or invalid
file missing: /Applications/Numbers.app/Contents/SharedSupport/Templates/01_Running_Log/es_419.lproj/Localizable.strings
file missing: /Applications/Numbers.app/Contents/SharedSupport/Templates/01_Simple_Charts/sv.lproj/LocalizableStyleNames.strings
.
.
.
Hmmm. Doesn’t like that I removed these, but Numbers continues to work just fine.
