### ISSUE TITLE
Removing folder symlinks causes Gatekeeper to report apps as damaged

### ISSUE THREAD

**Issue by SeanMSmith** [IngmarStein/Monolingual#19]
Monolingual 1.6.3 removes symbolic links to .lproj folders, which can cause Gatekeeper in both OS X 10.9.5 and OS X 10.10.2 to report that an application "is damaged and can't be opened."

This happens even when the CodeResources rules specify "optional" for <key>^Resources/.*\.lproj/</key> and when removing an actual folder would not cause Gatekeeper verification to fail.

Such symbolic links to folders are ubiquitous, being found almost everywhere Sparkle is used (e.g. in Monolingual itself).

Note that this issue will not manifest if the user has once successfully launched a particular version of an application before Monolingual removes symbolic links from that version.  (Hence if the user always updates an app through Sparkle, this problem will never occur with that app.)

However, if a user installs by dragging and dropping from a disk image a new app version that has never been launched before on the user's system and then runs Monolingual before launching the new version, Gatekeeper will report that the app "is damaged and can't be opened" (if the app contained symbolic links to .lproj folders, regardless of the CodeResources rules).  If the user has installed a large number of apps but has not launched them before running Monolingual, this could be a major annoyance.

I confirmed this issue with Downie 2.0 (<http://trial.charliemonroe.net/downie/download.php>), but given the widespread use of Sparkle, finding another app to test with should not be difficult.

**Comment by IngmarStein** [comment]
This is a serious bug, thanks for pointing my attention to it. I will have a look at it.

**Comment by IngmarStein** [comment]
I've uploaded 1.6.4b2 which should fix the issue. Could you please verify it?
In case you've previously installed 1.6.4b1, you'll need to delete /Library/PrivilegedHelperTools/net.sourceforge.MonolingualHelper because the helper process has changed but its version number has not.

**Comment by SeanMSmith** [comment]
I've just tested against Monolingual 1.6.4 and am sorry to report that the problem is only partially corrected.

In two applications that I drag-installed afresh, Downie 2.0 (http://software.charliemonroe.net/downie.php) and App Tamer 2.0.5 (http://www.stclairsoft.com/AppTamer/index.html), Monolingual 1.6.4 correctly left in place the symbolic link Contents/Frameworks/Sparkle.framework/Versions/A/Resources/fr_CA.lproj, but it still removed the symbolic link Contents/Frameworks/Sparkle.framework/Versions/A/Resources/pt.lproj, causing Gatekeeper to report both apps as damaged.

**Comment by IngmarStein** [comment]
I've tested 1.6.4 on Downie 2.0 and this is how Sparkle's resources directory looks on my computer after running Monolingual:
```
$ ll Downie.app/Contents/Frameworks/Sparkle.framework/Resources/
total 64
drwxr-xr-x@ 374B ./
drwxr-xr-x@ 204B ../
-rw-r--r--@ 1,1K Info.plist
-rw-r--r--@ 2,5K License.txt
-rw-r--r--@ 6,1K SUModelTranslation.plist
-rw-r--r--@ 6,4K SUStatus.nib
drwxr-xr-x@ 204B de.lproj/
drwxr-xr-x@ 238B en.lproj/
drwxr-xr-x@ 102B finish_installation.app/
lrwxr-xr-x    8B fr_CA.lproj@ -> fr.lproj
lrwxr-xr-x   11B pt.lproj@ -> pt_BR.lproj
```
Both symlinks are left in place and the signature is still valid:
```
$ codesign -vvv --deep Downie.app/
--prepared:…/Downie.app/Contents/Frameworks/XUAboutWindow.framework/Versions/Current/.
--validated:…/Downie.app/Contents/Frameworks/XUAboutWindow.framework/Versions/Current/.
--prepared:…/Downie.app/Contents/Frameworks/Sparkle.framework/Versions/Current/.
--validated:…/Downie.app/Contents/Frameworks/Sparkle.framework/Versions/Current/.
--prepared:…/Downie.app/Contents/Frameworks/Paddle.framework/Versions/Current/.
--validated:…/Downie.app/Contents/Frameworks/Paddle.framework/Versions/Current/.
Downie.app/: valid on disk
Downie.app/: satisfies its Designated Requirement
```
Could you please check if 1.6.4's helper program has been updated correctly?
```
$ otool -s __TEXT __info_plist /Library/PrivilegedHelperTools/net.sourceforge.MonolingualHelper | xxd -r
kV<?xml ve.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleShortVersionString</key>
	<string>1.6.4</string>
	<key>CFBundleIdentifier</key>
	<string>net.sourceforge.MonolingualHelper</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>MonolingualHelper</string>
	<key>CFBundleVersion</key>
	<string>1.6.4</string>
	<key>SMAuthorizedClients</key>
	<array>
		<string>identifier net.sourceforge.Monolingual and certificate leaf[subject.CN] = &quot;Developer ID Application: ti und m AG&quot;</string>
	</array>
</dict>
</plist>
```

**Comment by SeanMSmith** [comment]
I don't have Xcode installed, so I can't run otool, but /Library/PrivilegedHelperTools/net.sourceforge.MonolingualHelper appears to be version 1.6.4.  (I never installed any of the 1.6.4 betas.)

**Comment by IngmarStein** [comment]
Just to be sure, could you check if the binary contains the string "1.6.4"?
```
$ grep -F "1.6.4" /Library/PrivilegedHelperTools/net.sourceforge.MonolingualHelper 
Binary file /Library/PrivilegedHelperTools/net.sourceforge.MonolingualHelper matches
```
There have been upgrade issues in the past when Developer ID was new.

**Comment by SeanMSmith** [comment]
Yes, the binary contains the string "1.6.4":

<dict>
	<key>CFBundleShortVersionString</key>
	<string>1.6.4</string>
	<key>CFBundleIdentifier</key>
	<string>net.sourceforge.MonolingualHelper</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>MonolingualHelper</string>
	<key>CFBundleVersion</key>
	<string>1.6.4</string>
	<key>SMAuthorizedClients</key>
	<array>
		<string>identifier net.sourceforge.Monolingual and certificate leaf[subject.CN] = &quot;Developer ID Application: ti und m AG&quot;</string>
	</array>
</dict>

Just to be sure, I trashed both the app and the helper a few minutes ago and reinstalled Monolingual 1.6.4, and got the same result as before:  Monolingual 1.6.4 removes the pt.lproj symlink, but leaves the fr_CA.lproj symlink in place.

**Comment by SeanMSmith** [comment]
If you check "Move language files to trash" in Monolingual 1.6.4's preferences, I think you'll find that your pr.lproj symlinks are also removed.  That setting seems to make the difference between the results you and I are seeing.

**Comment by IngmarStein** [comment]
"Move language files to trash" doesn't seem to make a difference for me: pt.lproj and fr_CA.lproj as still (broken) symlinks to pt_BR.lproj and fr.lproj, respectively.

**Comment by SeanMSmith** [comment]
After running Monolingual 1.6.4 last night on a freshly installed copy of Downie 2.0 with the "Move language files to trash" preference unchecked, Monolingual correctly removed all but the en.lproj language folders from Sparkle's Resources folder, and correctly left in place both the fr_CA.lproj and pt.lproj symlinks.

I just now rechecked "Move language files to trash" and reran Monolingual 1.6.4 on that same copy of Downie 2.0 (from which Monolingual had previously removed .lproj folders), and Monolingual left in place both of the (broken) symlinks.

However, I then trashed that copy of Downie 2.0 and drag-installed a fresh copy, and when I ran Monolingual 1.6.4 on that freshly installed copy (with the "Move language files to trash" preference checked), Monolingual once again trashed the pt.lproj symlink, leaving the fr_CA.lproj symlink in place.

Please let me know if there's any other information I can give you, or anything else I can do, to help you track down this bug.

**Comment by IngmarStein** [comment]
Thanks for your investigation. I think I've found the issue and it will be fixed in the next release.

**Comment by SeanMSmith** [comment]
I can confirm that Monolingual 1.6.5 appears to correct the problem for Yosemite users.  Whether the "Move language files to trash" preference is checked or unchecked, Monolingual 1.6.5 leaves all symlinks in place in my limited testing.

Perhaps a Monolingual 1.5.11 would be in order for Mavericks users?  Although I no longer have a Mavericks system on which to test, it seems likely that the same problem affects Monolingual 1.5.10, and I know from experience that removing folder symlinks by hand in OS X 10.9.5 from apps not previously launched will cause Gatekeeper to report those apps as damaged.
