### ISSUE TITLE
Exclude Steam client app

### ISSUE THREAD

**Issue by SeanMSmith** [IngmarStein/Monolingual#22]
The Steam client application automatically repairs itself upon being launched after its language resources have been removed, restoring the removed resources, so Monolingual might as well exclude it.

**Comment by IngmarStein** [comment]
I'll add it to the blacklist. Do you happen to know the application's bundle identifier?

**Comment by SeanMSmith** [comment]
The Steam client's bundle identifier is "com.valvesoftware.steam".
