### ISSUE TITLE
“Space saved: Zero KB”

### ISSUE THREAD

**Issue by ghost** [IngmarStein/Monolingual#24]
Not sure what’s causing it, but I suspect that it may have something to do with the setting “Move language files to trash”.

**Comment by IngmarStein** [comment]
Yes, if you move the files to the trash, you don't actually space until you empty it. That's why Monolingual reports 0 KB.

**Comment by Eitot** [comment]
Perhaps you could change the string into “Files removed and moved to trash” or something similar.
Does the setting “Move language files to trash” only work for language files? Haven’t tried removing architectures yet.

**Comment by IngmarStein** [comment]
You're absolutely right, but string changes are quite costly because I need to contact all the translators. Feel free to create a PR, though!
Architectures can't be moved to the trash as they're part of fat binaries and not separate files.

**Comment by Eitot** [comment]
It might be enough to just suppress that part of the string.

However, I’m having trouble building the project on my system, to update the loc.string files. I installed the pods, but I’m still getting a compile error in Monolingual-Bridging-Header.h with respect to SMJobKit (‘file not found’). Not sure where the problem lies, I’m not that familiar with Xcode yet.

**Comment by IngmarStein** [comment]
The project uses [CocoaPods](http://cocoapods.org) for dependency management. You have to install that first and run ```pod install```.

**Comment by Eitot** [comment]
Yes, I did that. However, I did receive an error message in Terminal after using pod install: “[!] Pods written in Swift can only be integrated as frameworks; this feature is still in beta. Add `use_frameworks!` to your Podfile or target to opt into using it.” I added that line to the podfile and then the pod install continued without any problems. In Xcode, however, SMJobKit is still ‘not found’.

**Comment by IngmarStein** [comment]
Have you cloned the current trunk? The Podfile there already contains ```use_frameworks!```

**Comment by Eitot** [comment]
I started from scratch again.
(1) Cloned
(2) pod install (no errors)
(3) Removed code signing from Project > Build Settings
(4) Removed signing from Target > General
(5) Clicked on Product > Build

Now I get an error in MonolingualHelperClient.swift: “import SMJobKit” -> No such module

Any ideas?

**Comment by IngmarStein** [comment]
Did you open Monolingual.xcworkspace or Monolingual.xcodeproj? You should use the former.

**Comment by Eitot** [comment]
OK, I tried that. Now I get another error in that same file: use of undeclared type ‘SMJClient’

**Comment by IngmarStein** [comment]
git pull && pod update should help.

**Comment by Eitot** [comment]
Great, got it to work! Thanks for your help (and patience!)

**Comment by IngmarStein** [comment]
Cleaning old tickets.
