### ISSUE TITLE
Exclude path in program Prefereces

### ISSUE THREAD

**Issue by MiklB2** [IngmarStein/Monolingual#250]
Please, add Exclude path in program Preferences, not only Include directories (path).
Some apps (Onedrive, expl.) stop working (can't start) after deleting LP.
Framework HockeySDK checking listed LP every OneDrive start. See the log below.

[OneDrive-ERR-2020-12-09-155913.log](https://github.com/IngmarStein/Monolingual/files/5683472/OneDrive-ERR-2020-12-09-155913.log)

**Comment by IngmarStein** [comment]
To exclude a path, you can uncheck the boxes next to a path in the preference pane. You can skipp a path when removing language files, trimming architectures, or both.

**Comment by MiklB2** [comment]
Is it right? Like this? See att.
Unchecked path will excluded?

<img width="721" alt="monoligual" src="https://user-images.githubusercontent.com/62497613/102256211-2528d800-3f1c-11eb-9c47-9cb33fac0e65.png">

**Comment by IngmarStein** [comment]
Yep, that looks good.
