### ISSUE TITLE
ro.lproj

### ISSUE THREAD

**Issue by eugeniums** [IngmarStein/Monolingual#27]
Hey! How do I made a ro.lproj FOLDER to put all needed file in? I can not figure out here... 

Something like : 

eugeniums/Monolingual/ro.lproj 
or
IngmarStein/Monolingual/ro.lproj 

I have no idea... 

Any Idea?

I put them here : https://github.com/eugeniums/ro.lproj-for-Monolingual

still on working... not the final version... but are here...

**Comment by IngmarStein** [comment]
Want to submit a pull request?

**Comment by eugeniums** [comment]
yes... but I found out how to do what I want... 
work on this now... 

https://github.com/eugeniums/Monolingual/tree/master/ro.lproj
https://github.com/eugeniums/Monolingual/blob/master/GNU.txt
