### ISSUE TITLE
Defaulting into removing resources compiled for haswell, on a broadwell mac.

### ISSUE THREAD

**Issue by Wokiis** [IngmarStein/Monolingual#32]
Hello! I installed 1.6.7 today and noticed that it wanted to remove "Intel 64 Bit (Haswell)" as default when running it on my Broadwell (rMBP 2015) machine.

Since a Broadwell machine should be able to make use of whatever advantage the Haswell had, I think this might be a mistake and that it doesn't recognise Broadwell as "Haswell compatible", thus wanting to remove files that might be of use.

I don't know if it has any consequence or if it's an issue at all, but thought I might as well bring some attention to it. :)

**Comment by IngmarStein** [comment]
Yeah, I've already changed that. It should have no consequences, as I'm not aware of any program which actually has a x86_64h slice.

**Comment by minamhere** [comment]
I have the 2015 rMBP and noticed that Monolingual (downloaded today) still defaults to remove the Haswell files. I'm sure there's no impact, but just FYI that it still appears to remove by default.

**Comment by IngmarStein** [comment]
Yes, there hasn't been a release which includes the fix. The version after 1.6.7 will have it.
