### ISSUE TITLE
Has Monolingual been abandoned?

### ISSUE THREAD

**Issue by Kurt-Lang** [IngmarStein/Monolingual#341]
1.8.2 has been the "latest" release for quite some time. It doesn't even recognize an M1 or M2 Mac, which it tells you has an Intel 64-bit CPU. And you always have to remember to uncheck ARM at the top, as I did here, so it doesn't remove Apple Silicon native code.

![Screenshot 1](https://github.com/IngmarStein/Monolingual/assets/10281201/bb78a636-b0b9-43b4-bffc-2ab30f8b1d74)

**Comment by IngmarStein** [comment]
Sorry, I have very little time for Monolingual these days, but I'd appreciate contributions. Feel free to send a PR and I'll review.

**Comment by Kurt-Lang** [comment]
No problem. I kind of figured this app had fallen to the wayside. And with macOS completely locked down, there isn't much to remove anymore as most of the language data came from the OS and its installed apps.

About the only real exception is the MS Office apps, which become literally gigabytes smaller when the unnecessary languages are removed. And I don't even have that suite anymore. We replaced it with SoftMaker Office.

I'll likely just remove the app and not think about trying to save .01% of space. 🙂 But thank you for the time and support you did put into this app over the years.
