### ISSUE TITLE
Wish for this project to come back soon!!!!!!!!

### ISSUE THREAD

**Issue by JohnnyFireOne** [IngmarStein/Monolingual#353]
@IngmarStein 
i really wanna see this project rise again! updated and fully loaded!

**Comment by IngmarStein** [comment]
Yeah, it would be nice, but that will take a significant amount of time which I don't have. The project is open to contributions, though.

The usefulness of Monolingual has declined with every macOS release when more things were locked down (see https://github.com/IngmarStein/Monolingual/issues/318 for example).

The codebase is not in a good shape: it's halfway through a transition to SwiftUI which was never completed.

The API used to installed the privileged helper ([`SMJobBless`](https://developer.apple.com/documentation/servicemanagement/smjobbless(_:_:_:_:))) is deprecated and needs to be replaced with `SMAppService`

I don't haven have an Apple developer account anymore to notarize and sign a release.

**Comment by JohnnyFireOne** [comment]
> Yeah, it would be nice, but that will take a significant amount of time which I don't have. The project is open to contributions, though.
> 
> 
> 
> The usefulness of Monolingual has declined with every macOS release when more things were locked down (see https://github.com/IngmarStein/Monolingual/issues/318 for example).
> 
> 
> 
> The codebase is not in a good shape: it's halfway through a transition to SwiftUI which was never completed.
> 
> 
> 
> The API used to installed the privileged helper ([`SMJobBless`](https://developer.apple.com/documentation/servicemanagement/smjobbless(_:_:_:_:))) is deprecated and needs to be replaced with `SMAppService`
> 
> 
> 
> I don't haven have an Apple developer account anymore to notarize and sign a release.

I really really wish for it!!!! Hope a Christmas wish goes up!!!
