### ISSUE TITLE
Remove language files from `.help` packages?

### ISSUE THREAD

**Issue by derhuerst** [IngmarStein/Monolingual#36]
OS X and all applications have a lot of help packages. Because Monolingual removes certain languages of Applications anyway, removing the unnessecary language files for their help packages would save disk space.

To get an idea what I'm talking about run the following.

```shell
sudo find -E / -type d -regex '.*\.help$' -exec du -h -d 0 '{}' \;
```

**Comment by IngmarStein** [comment]
As far as I can tell, help packages contain localized resources in the standard locations, i.e. Contents/Resources/*.lproj. That means, Monolingual already processes those bundles when it traverses the parent application.

**Comment by derhuerst** [comment]
Okay, your're right; Monolingual removes the localied resources *inside* `.app` bundles. But what about global packages? In my opinion, they're supposed to handled by Monolingual as well.

**Comment by IngmarStein** [comment]
If you add the folder which contains the "global package", Monolingual will process it as well - it's not bound to just applications.

**Comment by derhuerst** [comment]
Oh, I didn't notice that's possible. Thanks!
