### ISSUE TITLE
Command line option for Monolingual?

### ISSUE THREAD

**Issue by bighungry** [IngmarStein/Monolingual#37]
I'm looking to use Monolingual as part of my system imaging process. Is there any way to run it from the command line as part of a shell script? I didn't see any references to that capability in the documentation.

**Comment by IngmarStein** [comment]
No, there's currently no command line interface for Monolingual, but this makes for a nice feature request. I would probably add that to the helper which does the actual work of removing files.

**Comment by IngmarStein** [comment]
The last commit adds the following command line interface to the helper:

```
Usage: ./net.sourceforge.MonolingualHelper [options]
  -u, --uninstall:
      Uninstall helper.
  -v, --version:  
      Print version and exit.
  -n, --dry:      
      Dry run: don't make any changes to the filesystem.
  -s, --strip:    
      Strip debug info from executables.
  -t, --trash:    
      Don't delete files but move them to the trash.
  -i, --include:  
      Include directory.
  -x, --exclude:  
      Exclude directory.
  -b, --bundle:   
      Exclude a bundle from processing (e.g. "com.apple.iPhoto").
  -d, --delete:   
      Name of a file or directory to delete (e.g. "fr.lproj").
  -t, --thin:     
      Remove architecture from universal binary (e.g. "ppc").
```

You can use it like this:

```./net.sourceforge.MonolingualHelper --include /Applications --exclude "/Applications/Adobe Photoshop CC 2014" --delete fr.lproj --delete it.lproj```

Please note that the helper does not automatically use the blacklist from https://ingmarstein.github.io/Monolingual/blacklist.plist. In case you want to exclude certain bundles, you have to add those via "-b" yourself.

Does that fit your needs?

**Comment by bighungry** [comment]
To clarify the usage, does each localization need to be named explicitly, i.e. --delete it.lproj --delete fr.lproj etc., or is there some way to say keep English but delete everything else? This would be handy in the GUI as well. Like a preset maybe?

**Comment by IngmarStein** [comment]
Right now, each localization needs to be specified explicitly. To minimize the risk of accidentally removing the wrong files, the helper (which is a privileged process running as root), does not compare file names to patterns - you need to name all the the things you want to have removed. If you want to create a pull request, I'd take a look, though.

**Comment by IngmarStein** [comment]
Closed due to lack of feedback.
