### ISSUE TITLE
Deleted my English files - Mac won't boot

### ISSUE THREAD

**Issue by ferologics** [IngmarStein/Monolingual#38]
I wanted to reinstall, dont have enough space to do so, can't empty my trash because it's read only directory, I'm stuck.

Can't find a way to login as root in single user mode.

Thx

**Comment by IngmarStein** [comment]
Yes, you can shoot yourself in the foot when removing needed stuff. Monolingual warns before removing English, but you can ignore the warning.

**Comment by ferologics** [comment]
lol. it's cool project though... just make it less hazardous I guess
