### ISSUE TITLE
Delete resources from LPDF bundles

### ISSUE THREAD

**Issue by bumblebritches57** [IngmarStein/Monolingual#41]
LPDF files contain *.lproj bundles just like .frameworks, among others do, you should check those files for resources as well, and delete all of them except the excluded ones of course.

**Comment by bumblebritches57** [comment]
For example: /Volumes/El Capitan/Applications/Utilities/System Information.app/Contents/Resources/ProductGuides contains over 200mb of pdf localizations in about a dozen files, for further example: regulatory-022-00432.lpdf

**Comment by IngmarStein** [comment]
Have you tried adding /Volumes/El Capitan/Applications to Monolingual's location list (in the preferences)? Monolingual inspects all kinds of bundles, not just applications.

**Comment by bumblebritches57** [comment]
I manually removed them (because I'm an idiot), and this never occurred to me to try, I'll try finding another lpdf and adding it to the search location.

**Comment by IngmarStein** [comment]
Closed due to lack of feedback.
