### ISSUE TITLE
Compatibility with El Capitan

### ISSUE THREAD

**Issue by ghost** [IngmarStein/Monolingual#42]
Is Monolingual compatible with El Capitan? I suspected that System Integrity Protection would block any attempt at removing language files from protected locations, but I just saw a post that suggests another problem as well: http://forums.macrumors.com/threads/os-x-10-11-all-the-little-things.1890519/page-43#post-21680183.

**Comment by IngmarStein** [comment]
SIP is not a problem, it just protects localizations in a few locations (/System, /bin, /sbin and /usr excl. /usr/local). I haven't seen the other issue, but I will test on the next beta.
