### ISSUE TITLE
Broken signing in /Library/Filesystems/* ?

### ISSUE THREAD

**Issue by Lethos** [IngmarStein/Monolingual#50]
On 10.11 after having run ML1.7.1 at least Tuxera NTFS was not running. It's a "64bit" system, and I had removed "32bit" (which was default, I think). (Sadly there was a few days in between, so I cannot relate this to 100%.)

As far as I can tell, the integrity of the signed .kext bundles was broken. (Error message about the kext not loading; verified invalid signing via kextutil.)
A re-installation of Tuxera NTFS solved the issue.
Could it be, ML removed files from the bundle, and the signature from the developers certificate did not match any more (due to changed bundle content)?

**Comment by IngmarStein** [comment]
That would be unusual. All the slices ("architectures") in a Mach-O binary are signed individually and it's documented by Apple that removing a slice for a particular architecture doesn't invalidate the code signature (https://developer.apple.com/library/mac/technotes/tn2206/_index.html)
Could you try processing that software with Monolingual again and then run ```codesign -vvv /Library/Filesystems/…```  on it?

**Comment by Lethos** [comment]
(Sorry for the delay.)
I've re-ran Monolingual 1.7.2 specifically on ```/Library/Filesystems/``` - it deleted a small part from Tuxera NTFS, but did not invalidate the signing. (Your command shows "everything green".) Also the SW itself works as intended.
Hmhh. I'm than at a loss, as to what caused the bundles to be "corrupted" - but it seems Monolingual is not to blame. Sorry, was my best guess.
