### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by DotTheI** [IngmarStein/Monolingual#52]
I would like to translate the application to Russian

**Comment by IngmarStein** [comment]
Cool! Feel free to submit a pull request, I'll merge it.

**Comment by DotTheI** [comment]
@IngmarStein Not sure how to do that and which files need to be translated

**Comment by IngmarStein** [comment]
Here's a nice tutorial how to create pull requests on GitHub. In case that's too complicated, just attach the files to this issue and I'll merge them. You'll find the files which need to be translated in the en.lproj folder (https://github.com/IngmarStein/Monolingual/tree/master/Resources/en.lproj).

**Comment by DotTheI** [comment]
@IngmarStein The link to the instruction must've been stripped. Anyway, here you go https://yadi.sk/d/xwvWVj-CjrYhk

**Comment by IngmarStein** [comment]
Here's a link to a beta version which includes your translation. Please let me know if the strings are fine:
https://www.dropbox.com/s/0yxe62qnuvv9nu4/Monolingual-1.7.3.dmg?dl=0

**Comment by DotTheI** [comment]
@IngmarStein I can't download the file. Keep getting the "There was a problem completing this request" error

**Comment by IngmarStein** [comment]
It works for me… can you try again?

**Comment by DotTheI** [comment]
@IngmarStein Got it! I made a few changes. Before I resubmit them, may you please clarify what 'Strip debug info when removing architectures' means, so that I can translate it properly?

**Comment by IngmarStein** [comment]
Some developers forget to remove debug information from apps they ship. This data is useless to the normal user and only takes up space, hence Monolingual offers the ability to strip that data from the binaries. The functionality became less effective in the age of code signing, as it would invalidate the signature and hence Monolingual ignores signed binaries.

**Comment by DotTheI** [comment]
@IngmarStein Thank you! Here you go: https://yadi.sk/d/D8HKqdaIjxLwx

**Comment by IngmarStein** [comment]
That ZIP file seems to be broken:
```
$ file ru.lproj.zip 
ru.lproj.zip: data
$ unzip ru.lproj.zip 
Archive:  ru.lproj.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of ru.lproj.zip or
        ru.lproj.zip.zip, and cannot find ru.lproj.zip.ZIP, period.
```

**Comment by DotTheI** [comment]
@IngmarStein Oh. Please try this https://yadi.sk/d/D8HKqdaIjxLwx

**Comment by IngmarStein** [comment]
I've updated the file on Dropbox. Please have a look if you're happy with the translation.

**Comment by DotTheI** [comment]
@IngmarStein I corrected a typo and made some improvements to the translation. The file has been updated https://yadi.sk/d/D8HKqdaIjxLwx It's good to go!

**Comment by IngmarStein** [comment]
Thanks again! Will be part of the next release.
