### ISSUE TITLE
Not a direct issue with Monolingual, but something you may want to know.

### ISSUE THREAD

**Issue by JKLStudiosInc** [IngmarStein/Monolingual#55]
I was looking for the Monolingual site to check on the version, and couldn't remember the URL. So I just typed monolingual into Google. The top choice presented was www. monolingual .com . I knew that wasn't it, but figured maybe you had also obtained that domain name so you could catch users trying to find your app that way.

Nope, it's a one of those idiotic scam sites that forwards you to the now common JavaScript poup loop of "Your Mac is infected! Call 1-800-xxx-xxx now for immediate help!" Where they will fleece you out of as much money as you're willing to cough up.

I though you may want to know this (if you don't already) and send out emails to SpamHaus and other spam/extortion server blacklisting services to get it removed or blocked.

**Comment by IngmarStein** [comment]
Thanks for spotting that. I've reported the URL to Google's Safe Browsing team in the hope it ends up on the blacklist. However, I don't have a trademark on the name "Monolingual", so I can't take any legal action again that site's owner.
SpamHaus is probably not the right blacklist as they are more concerned about email spam. Do you have any other ideas how I could stop monolingual.com?

**Comment by JKLStudiosInc** [comment]
Wish I did. But I'm not sure how to go about getting a scam site blocked.

**Comment by IngmarStein** [comment]
This is the WHOIS data for monolingual.com:
```
Domain Name: MONOLINGUAL.COM
Registry Domain ID: 86275871_DOMAIN_COM-VRSN
Registrar WHOIS Server: whois.enom.com
Registrar URL: www.enom.com
Updated Date: 2015-08-11T03:55:27.00Z
Creation Date: 2002-05-05T17:21:00.00Z
Registrar Registration Expiration Date: 2018-05-05T17:21:00.00Z
Registrar: ENOM, INC.
Registrar IANA ID: 48
Domain Status: clientTransferProhibited https://www.icann.org/epp#clientTransferProhibited
Registry Registrant ID: 
Registrant Name: DOMAIN SUPPORT
Registrant Organization: 
Registrant Street: 1/F YALLY INDUSTRIAL BUILDING
Registrant City: WONG CHUK HANG
Registrant State/Province: NA
Registrant Postal Code: 
Registrant Country: HK
Registrant Phone: +852.91441424
Registrant Phone Ext: 
Registrant Fax: 
Registrant Fax Ext:
Registrant Email: support@DOMAINNAMEZ.COM
Registry Admin ID: 
Admin Name: DOMAIN SUPPORT
Admin Organization: 
Admin Street: 1/F YALLY INDUSTRIAL BUILDING
Admin City: WONG CHUK HANG
Admin State/Province: NA
Admin Postal Code: 
Admin Country: HK
Admin Phone: +852.91441424
Admin Phone Ext: 
Admin Fax: 
Admin Fax Ext:
Admin Email: support@DOMAINNAMEZ.COM
Registry Tech ID: 
Tech Name: DOMAIN SUPPORT
Tech Organization: 
Tech Street: 1/F YALLY INDUSTRIAL BUILDING
Tech City: WONG CHUK HANG
Tech State/Province: NA
Tech Postal Code: 
Tech Country: HK
Tech Phone: +852.91441424
Tech Phone Ext: 
Tech Fax: 
Tech Fax Ext: 
Tech Email: support@DOMAINNAMEZ.COM
Name Server: NS1.HASTYDNS.COM
Name Server: NS2.HASTYDNS.COM
DNSSEC: unSigned
Registrar Abuse Contact Email: abuse@enom.com
Registrar Abuse Contact Phone: +1.4252982646
URL of the ICANN WHOIS Data Problem Reporting System: http://wdprs.internic.net/
Last update of WHOIS database: 2015-08-11T03:55:27.00Z
```
I'll write a mail to the abuse contact address.

**Comment by JKLStudiosInc** [comment]
Good choice! Hopefully, the registrar will do something about it. I've read far too often regarding China, Russian and other eastern and mideast countries that many times, they simply don't care and won't do anything even when you report it.

**Comment by IngmarStein** [comment]
Haven't heard back from them :-1:
