### ISSUE TITLE
iMovie crashes

### ISSUE THREAD

**Issue by DotTheI** [IngmarStein/Monolingual#56]
iMovie 10.1 crashes after removing unwanted architectures. Languages removal doesn't result in that behavior though. From the logs:

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Symbol not found: _cthread_set_errno_self
  Referenced from: /usr/libexec/hasplmd
  Expected in: /usr/lib/libSystem.B.dylib
 in /usr/libexec/hasplmd

**Comment by IngmarStein** [comment]
Cleaning old tickets.
