### ISSUE TITLE
Architectures selected by default

### ISSUE THREAD

**Issue by DotTheI** [IngmarStein/Monolingual#57]
Ever since 1.71 the Haswell architecture is not selected by default, so I have to select it manually every time I run the application:
![screen shot 2015-10-22 at 10 19 26 pm](https://cloud.githubusercontent.com/assets/10737439/10685948/2b881536-7914-11e5-8345-00d562087f87.png)
I am on OS X 10.11.1, late 2011 MBP

**Comment by IngmarStein** [comment]
That's just a safe default. If you later decide to buy a new Mac and want to migrate all your data (incl. apps), you'll want to have the Haswell-optimized binaries (of which there are not many).

**Comment by DotTheI** [comment]
Thank you!
