### ISSUE TITLE
Sticky Language removal

### ISSUE THREAD

**Issue by BruceRutland** [IngmarStein/Monolingual#58]
Been loving Monolingual for forever –– well a long time anyway... :)

It would be great/ if the preferences would 'keep' the settings of the language(s) to be removed– Im forever having to set them same language and localisations, to be removed, each time I use Monolingual 

thanks
Bruce

**Comment by IngmarStein** [comment]
From http://ingmarstein.github.io/Monolingual/faq.html:

Q. Monolingual doesn't remember my preferences of which languages to remove.
A. Monolingual by default removes those languages that are not listed in System Preferences / International / Languages.
