### ISSUE TITLE
Offer a resumed way to choose languages

### ISSUE THREAD

**Issue by lunarbase** [IngmarStein/Monolingual#60]
Do we really have to click on 1000 languages to remove them?
I would prefer just to have a general list of languages, like portuguese, spanish, english etc.
That and the fact that monolingual does not stores the languages we choose the first time, make the app annoying, having to select the thousand languages over and over...
please!

**Comment by IngmarStein** [comment]
You only need to click on 1000 languages if you want to keep that many. A checked entry means that it will be removed. Monolingual reads your settings from Settings / Country and Region.

**Comment by lunarbase** [comment]
can at least monolingual save the languages I choose and read that the next time it launches?

**Comment by IngmarStein** [comment]
Monolingual reads your settings from System Preferences "Settings / Country and Region". It assumes that you only want to keep the languages that OS X is configured to actually use. It usually makes no sense to keep the language files for a language that the OS doesn't look for.

**Comment by lunarbase** [comment]
I speak several languages. Sorry but every time you let a software assume something about the user it will always go wrong. Better let the user decide.

**Comment by IngmarStein** [comment]
Then you probably have enabled all the languages you speak in System Preferences, right?
