### ISSUE TITLE
please fix zh-Hans.lproj and zh-Hant.lproj (and other xx-xx.lproj)

### ISSUE THREAD

**Issue by citovsky** [IngmarStein/Monolingual#62]
please fix zh-Hans.lproj and zh-Hant.lproj (and other xx-xx.lproj) recognition. presently these are not removed. thanks

**Comment by IngmarStein** [comment]
Should be fixed in 1.7.4.

**Comment by citovsky** [comment]
thanks


--------------------------
Vitaly Citovsky
Department of Biochemistry and Cell Biology
State University of New York
Stony Brook, NY 11794-5215
Tel.: 631.632.9534
Fax: 631.632.8575
E-mail: vitaly.citovsky@stonybrook.edu
😄
