### ISSUE TITLE
Can't empty trash with the latest version of Monolingual

### ISSUE THREAD

**Issue by GhislainD** [IngmarStein/Monolingual#63]
Hello,

I got the following message after having launched the latest version of Monolingual: "You don't have rights to remove the following files:
Impossible de supprimer « BKBaseBrowserModule.nib » car vous ne disposez pas de l’autorisation nécessaire pour y accéder.
Impossible de supprimer « BKBaseContentsModule.nib » car vous ne disposez pas de l’autorisation nécessaire pour y accéder.
Impossible de supprimer « BKBrowserControlsModule.nib » car vous ne disposez pas de l’autorisation nécessaire pour y accéder.
Impossible de supprimer « BKBrowserControlsModuleGrayLarge.nib » car vous ne disposez pas de l’autorisation nécessaire pour y accéder.
Impossible de supprimer « BKBrowserModule.nib » car vous ne disposez pas de l’autorisation nécessaire pour y accéder.
Impossible de supprimer « BKColumnHierarchyModule.nib » car vous ne disposez pas de l’autorisation nécessaire pour y accéder.
Impossible de supprimer « BKColumnHierarchyModuleAquaCongruency.nib » car vous ne disposez pas de l’autorisation nécessaire pour y accéder.
Impossible de supprimer « BKDetailListModule.nib » car vous ne disposez pas de l’autorisation nécessaire pour y accéder.
Impossible de supprimer « BKDetailListModuleAquaCongruency.nib » car vous ne disposez pas de l’autorisation nécessaire pour y accéder.
Impossible de supprimer « BKDetailListModuleGrayLarge.nib » car vous ne disposez pas de l’autorisation nécessaire pour y accéder.
Impossible de supprimer « BKFilterQueryModule.nib » car vous ne disposez pas de l’autorisation nécessaire pour y accéder.
Impossible de supprimer « BKFilterQueryTile.nib » car vous ne disposez pas de l’autorisation nécessaire pour y accéder.
Impossible de supprimer « BKFilterQueryTileAquaCongruency.nib » car vous ne disposez pas de l’autorisation nécessaire pour y accéder.
Impossible de supprimer « BKGridModule.nib » car vous ne disposez pas de l’autorisation nécessaire pour y accéder.
Impossible de supprimer « BKGridModuleAquaCongruency.nib » car vous ne disposez pas de l’autorisation nécessaire pour y accéder.
Impossible de supprimer « BKGridModuleGrayLarge.nib » car vous ne disposez pas de l’autorisation nécessaire pour y accéder.
Impossible de supprimer « BKItemKeyLocalizations.plist » car vous ne disposez pas de l’autorisation nécessaire pour y accéder.
Impossible de supprimer « BKItemKeys.strings » car vous ne disposez pas de l’autorisation nécessaire pour y accéder.
Impossible de supprimer « BKItemsControlsModule.nib » car vous ne disposez pas de l’autorisation nécessaire pour y accéder.
Impossible de supprimer « BKItemsControlsModuleAquaCongruency.nib » car vous ne disposez pas de l’autorisation nécessaire pour y accéder.
Impossible de supprimer « BKListModule.nib » car vous ne disposez pas de l’autorisation nécessaire pour y accéder.
Impossible de supprimer « BKListModuleAquaCongruency.nib » car vous ne disposez pas de l’autorisation nécessaire pour y accéder.
Impossible de supprimer « BKMenuedFilterQueryTile.nib » car vous ne disposez pas de l’autorisation nécessaire pour y accéder.
Impossible de supprimer « BKMenuedFilterQueryTileAquaCongruency.nib » car vous ne disposez pas de l’autorisation nécessaire pour y accéder.
Impossible de supprimer « BKOutlineModule.nib » car vous ne disposez pas de l’autorisation nécessaire pour y accéder.
Impossible de supprimer « BKOutlineModuleAquaCongruency.nib » car vous ne disposez pas de l’autorisation nécessaire pour y accéder.
Impossible de supprimer « BKPredicateEditorLocalizations.strings » car vous ne disposez pas de l’autorisation nécessaire pour y accéder.
Impossible de supprimer « BKPredicateEditorModule.nib » car vous ne disposez pas de l’autorisation nécessaire pour y accéder.
Impossible de supprimer « BKPredicateEditorModuleAquaCongruency.nib » car vous ne disposez pas de l’autorisation nécessaire pour y accéder.
Impossible de supprimer « BKPreviewModule.nib » car vous ne disposez pas de l’autorisation nécessaire pour y accéder.
Impossible de supprimer « BKSidebarBrowserContentsModule.nib » car vous ne disposez pas de l’autorisation nécessaire pour y accéder.
Impossible de supprimer « BKSidebarBrowserModule.nib » car vous ne disposez pas de l’autorisation nécessaire pour y accéder.
Impossible de supprimer « BKSidebarModule.nib » car vous ne disposez pas de l’autorisation nécessaire pour y accéder.
Impossible de supprimer « BKSplitWithExtrasModule.nib » car vous ne disposez pas de l’autorisation nécessaire pour y accéder.
Impossible de supprimer « BKStandardBrowserModule.nib » car vous ne disposez pas de l’autorisation nécessaire pour y accéder.
Impossible de supprimer « BrowserKit.strings » car vous ne disposez pas de l’autorisation nécessaire pour y accéder.

Any advise.
Many thanks in advance

**Comment by IngmarStein** [comment]
Does [this](https://support.apple.com/en-us/HT2963) (see section "Emptying the Trash") help?

**Comment by MPPMPP** [comment]
Same problem here.  Some of the files Monolingual put in the trash have read/write permission set for system only while other users have read only permission.  

That article on emptying the trash doesn't help and even using Terminal was unsuccessful. It's not possible to change the permissions on the files or even to put them back where they came from (wherever that is), so they just sit in the trash.  Can't Google up a solution, either.

I am attaching a screenshot of the folders in the trash, of the contents of the first folder, the first file in the first folder when opened as a text document, and of the permissions for the folder.  The permissions on the individual files in the folders are similar.

This is a new problem and is probably not really Monolinguals responsibility, but perhaps permissions should be checked and files should be skipped if the user won't be able to delete them.

Thanks for making this program available, I have been using it for a while now and it frees up a lot of space!

![screen shot 2015-12-08 at 8 51 33 pm](https://cloud.githubusercontent.com/assets/16216327/11674352/2c6882f2-9dee-11e5-951c-17079b9649e3.png)
![screen shot 2015-12-08 at 8 50 12 pm](https://cloud.githubusercontent.com/assets/16216327/11674353/2c69aec0-9dee-11e5-9dd5-6dffb4b2f414.png)
![screen shot 2015-12-08 at 8 53 05 pm](https://cloud.githubusercontent.com/assets/16216327/11674355/2c6dc9a6-9dee-11e5-9743-c6a2f7c3a4f6.png)
![screen shot 2015-12-08 at 8 50 49 pm](https://cloud.githubusercontent.com/assets/16216327/11674354/2c6c588c-9dee-11e5-8219-d147a072f5d9.png)

**Comment by GhislainD** [comment]
Hi,

Thanks you for copying me.
The proposed solution didn’t work for me neither.
Still searching.

Regards

Ghislain

**Comment by IngmarStein** [comment]
Do you happen to know to which application these files belong? Then I'll try to reproduce the issue.
Anyways, ```sudo rm -rf ~/.Trash/ ```should always work…

**Comment by GhislainD** [comment]
Hello,

I tried with rm -rf…
and I got
imac-g5-de-ghislain-delaunois:~ ghislaindelaunois$ rm -rf ~/.Trash/ 
rm: /Users/ghislaindelaunois/.Trash//zh_CN 7-53-54.lproj/BKBaseBrowserModule.nib: Operation not permitted
rm: /Users/ghislaindelaunois/.Trash//zh_CN 7-53-54.lproj/BKBaseContentsModule.nib: Operation not permitted
rm: /Users/ghislaindelaunois/.Trash//zh_CN 7-53-54.lproj/BKBrowserControlsModule.nib: Operation not permitted
rm: /Users/ghislaindelaunois/.Trash//zh_CN 7-53-54.lproj/BKBrowserControlsModuleGrayLarge.nib: Operation not permitted
rm: /Users/ghislaindelaunois/.Trash//zh_CN 7-53-54.lproj/BKBrowserModule.nib: Operation not permitted
rm: /Users/ghislaindelaunois/.Trash//zh_CN 7-53-54.lproj/BKColumnHierarchyModule.nib: Operation not permitted
rm: /Users/ghislaindelaunois/.Trash//zh_CN 7-53-54.lproj/BKColumnHierarchyModuleAquaCongruency.nib: Operation not permitted
rm: /Users/ghislaindelaunois/.Trash//zh_CN 7-53-54.lproj/BKDetailListModule.nib: Operation not permitted
rm: /Users/ghislaindelaunois/.Trash//zh_CN 7-53-54.lproj/BKDetailListModuleAquaCongruency.nib: Operation not permitted
rm: /Users/ghislaindelaunois/.Trash//zh_CN 7-53-54.lproj/BKDetailListModuleGrayLarge.nib: Operation not permitted
rm: /Users/ghislaindelaunois/.Trash//zh_CN 7-53-54.lproj/BKFilterQueryModule.nib: Operation not permitted…..
etc …

Sorry but it stil doesn’t work.

(I don’t remember the aps which generated this problem, appeared after an update from the App Store)

Regards,

Ghislain

**Comment by IngmarStein** [comment]
I think you're missing the important ```sudo```part of the command.

**Comment by MPPMPP** [comment]
I just tried several times copying & pasting "sudo rm -rf ~/.Trash/" into terminal and get each file listed this way:

rm: /Users/abc/.Trash//zh_CN 11-58-31.lproj: Operation not permitted

Then a final comment:

rm: /Users/abc/.Trash/: Directory not empty

I have no idea which program the files are associated with.  This started right after I upgraded to El Capitan, though I may have updated some other software, too.

**Comment by GhislainD** [comment]
Hello,

I managed to empty the trash, eventually.

In doing the following:
	* restart your computer in « Recovery » mode (cmd+R)
	* open Terminal
	* key in csrutil disable
	* restart and then empty Trash. 
	* Done.

Explanation is here (in French): http://www.mac4ever.com/actu/104738_el-capitan-retrouver-un-vrai-root-et-desactiver-le-system-integrity-protection <http://www.mac4ever.com/actu/104738_el-capitan-retrouver-un-vrai-root-et-desactiver-le-system-integrity-protection>

Regards,

Ghislain

**Comment by MPPMPP** [comment]
Thank you so much, Ghislain, that worked perfectly!  It is so nice to have an empty trash can again!  

Here are instructions in English, including instructions on how to turn the "System Integrity Protection" back on using the same process but keying in "csrutil enable" rather than "csrutil disable" in Terminal:
www.imore.com/el-capitan-system-integrity-protection-helps-keep-malware-away

It is a good idea to turn it back on for protection against malware:  https://support.apple.com/en-us/HT204899

**Comment by IngmarStein** [comment]
Is this still happening with the current version 1.7.3?
I think the issue was fixed in 1.7.2.

**Comment by MPPMPP** [comment]
Hello Ingmar,

I don't have any way of knowing because although I did run the new version
a couple of days ago, it wouldn't have encountered the same problem because
the offending files had already been deleted.

Thanks again for making and sharing this software!

Sincerely,
Margaret

*******
