### ISSUE TITLE
User interface issue

### ISSUE THREAD

**Issue by adamadman** [IngmarStein/Monolingual#64]
This is one-half user interface issue, one-half I just did something stupid.

ISSUE
The screen instructions on use of Monolingual can lead to a user error:

The program instructs you to "Select the languages you want to remove." But it opens with ALL LANGUAGES SELECTED (except English). On a very basic level, this is a fault in logic, because you are DESELECTING the languages you want to KEEP, rather than what the instructions say.

This means in fact the instructions should say to de- (or un-) select the languages you do NOT want to remove. But that's a double negative and can easily also lead to a user error. 

SUGGESTIONS
Instead, you could default to all checkboxes deselected, though this means a labour-intensive check-boxing process must follow. I think a happy medium would be: Have a default to all deselected and have a control where the user can choose "recommended deletions" and "all languages but English" (each of which pre-select a large set of languages -- the former deselecting all but the most commonly-used languages). But make the user make the choice. 

WHAT BROUGHT THIS UP
I being this up because, working on the computer at the end of an exhausting day and week, I followed the instructions literally and deselected all the languages I wanted to delete. Running the program then managed to delete a large set of languages I wanted to keep. Luckily, I realized it after about ten seconds and stopped the process, and so far I have not seen any bad effects to the system. However, I think this is a valid issue of slightly misleading screen instructions.

ALSO: NEED FOR A LOG
On a separate but related note, since the program does not have a log, I can tell you it would be great if the program logged what it had actually removed so I could see if I will likely face any problems. For example, I need German and French to be active, and have no idea if these were deleted before I stopped it. If there is a way to find this out, please tell me,  :-)  Please tell me if I should add this as a separate issue.

**Comment by IngmarStein** [comment]
Just a quick reply wrt. the log: it's in ~/Library/Logs/Monolingual.log

**Comment by adamadman** [comment]
Thank you for the quick reply! But you know what? I ran it from the dmg file without installing...so it apparently did not create the log. At least, I don't see any log.

**Comment by IngmarStein** [comment]
Did you find the log file in the end? I'll close this issue for now - please reopen if the log is not created.

**Comment by adamadman** [comment]
Dear Ingmar,

Regarding #64:  The computer kept working, so I believe I'll just go on and
hope that anything the shouldn't have been deleted will be reinstated with
the next system update.

But, no, the log was not created, so I don't really know what was deleted.

Let me reiterate my suggestion from a ways back, and that is that you
consider adjusting/augmenting the user interface. I can't remember my exact
suggestion; I believe it was to START with nothing selected and have a
"Select All" checkbox for someone who wants to do some serious deletions;
then allow them to uncheck what they want to keep. Or have a "All but the
big 10 [or some number] languages" that automatically selects all but the
most commonly-used languages for deletion, again then allowing the user to
personalize the list.

Many thanks,

-Adam-
