### ISSUE TITLE
Unable to delete language files in OS 10.11.2

### ISSUE THREAD

**Issue by ae6dx** [IngmarStein/Monolingual#66]
After upgrading to 10.11.2 I don't seem to be able to delete unneeded language files.  All apps apear to now be owned by root user.  i tried using Monolingual but no luck there either.

**Comment by IngmarStein** [comment]
Starting with 10.11, you can no longer modify system files (including language files) - that's part of System Integrity Protection. Monolingual can still remove all the language files from non-system apps.
