### ISSUE TITLE
iFFmpeg crashes

### ISSUE THREAD

**Issue by DotTheI** [IngmarStein/Monolingual#67]
iFFmpeg application won't start after clearing architectures:

Process:               iFFmpeg [56770]
Path:                  /Applications/iFFmpeg.app/Contents/MacOS/iFFmpeg
Identifier:            com.osxbytes.iffmpeg5
Version:               ???
Code Type:             X86 (Native)
Parent Process:        ??? [1]
Responsible:           iFFmpeg [56770]
User ID:               501

Date/Time:             2016-02-16 11:40:30.659 +0300
OS Version:            Mac OS X 10.11.2 (15C50)
Report Version:        11
Anonymous UUID:        7B7752D1-A1AE-77A3-9B73-746EE44A6E96

Sleep/Wake UUID:       B313A304-136D-41CE-8E26-EF96A89BF886

Time Awake Since Boot: 190000 seconds
Time Since Wake:       7900 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @executable_path/../Frameworks/XojoFramework.framework/Versions/A/XojoFramework
  Referenced from: /Applications/iFFmpeg.app/Contents/MacOS/iFFmpeg
  Reason: no suitable image found.  Did find:
	/Applications/iFFmpeg.app/Contents/MacOS/../Frameworks/XojoFramework.framework/Versions/A/XojoFramework: mach-o, but wrong architecture
	/Applications/iFFmpeg.app/Contents/MacOS/../Frameworks/XojoFramework.framework/Versions/A/XojoFramework: mach-o, but wrong architecture

Binary Images:
0x8fe62000 - 0x8fe965cf  dyld (360.18) <25D51D2B-794C-3911-9EEE-B1F0035D7104> /usr/lib/dyld
0x9153a000 - 0x9153bfff  libSystem.B.dylib (1226.10.1) <27769E06-CA74-3B99-8D82-2E95EFB49CCE> /usr/lib/libSystem.B.dylib

**Comment by IngmarStein** [comment]
This seems to be a common issue for which I need to find a solution:
iFFmpeg 5.x is a 32-bit application:
```
$ file /Volumes/iFFmpeg/iFFmpeg.app/Contents/MacOS/iFFmpeg 
/Volumes/iFFmpeg/iFFmpeg.app/Contents/MacOS/iFFmpeg: Mach-O executable i386
```
and it includes universal frameworks:
```
$ file /Volumes/iFFmpeg/iFFmpeg.app/Contents/Frameworks/XojoFramework.framework/Versions/A/XojoFramework 
/Volumes/iFFmpeg/iFFmpeg.app/Contents/Frameworks/XojoFramework.framework/Versions/A/XojoFramework: Mach-O universal binary with 2 architectures
/Volumes/iFFmpeg/iFFmpeg.app/Contents/Frameworks/XojoFramework.framework/Versions/A/XojoFramework (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
/Volumes/iFFmpeg/iFFmpeg.app/Contents/Frameworks/XojoFramework.framework/Versions/A/XojoFramework (for architecture i386):	Mach-O dynamically linked shared library i386
```

If you now ask Monolingual to remove the 32-bit slices, it will leave the main executable untouched (because the 32-bit slice is the only one) but remove them from the frameworks, which then become 64-bit-only. As a result, dyld is unable to load the frameworks because they don't match the main executable's architecture.

**Comment by IngmarStein** [comment]
Btw, iFFmpeg 6 is 64-bit and thus is not affected.

**Comment by DotTheI** [comment]
Oh, I didn't know about the 6th version. The case can be closed then :) Thank you!

**Comment by IngmarStein** [comment]
I want to fix this in a general way (and not just add iFFmpeg 5.x to the blacklist), so I leave this open and use this app as a test.
I'm thinking of a heuristic and not touch frameworks embedded in an app bundle if the main executable is a non-fat file. This is not perfect, but should protect users in most cases.
