### ISSUE TITLE
CrossOver crashes

### ISSUE THREAD

**Issue by DotTheI** [IngmarStein/Monolingual#68]
CrossOver application won't launch after clearing architectures
![2016-02-16 12 01 26](https://cloud.githubusercontent.com/assets/10737439/13071521/1d8005e2-d4a5-11e5-8d47-ef06db96e87d.png)
:

**Comment by IngmarStein** [comment]
Do you have a crashlog for this app?

**Comment by DotTheI** [comment]
I have this:

Process:               quartz-wm [85043]
Path:                  /Applications/CrossOver.app/Contents/SharedSupport/X11/bin/quartz-wm
Identifier:            quartz-wm
Version:               ???
Code Type:             X86 (Native)
Parent Process:        CrossOver [85038]
Responsible:           quartz-wm [85043]
User ID:               501

Date/Time:             2016-02-19 16:29:04.526 +0300
OS Version:            Mac OS X 10.11.2 (15C50)
Report Version:        11
Anonymous UUID:        7B7752D1-A1AE-77A3-9B73-746EE44A6E96

Sleep/Wake UUID:       C3C5E1D4-5609-48A9-9E01-CD75AB7DBADB

Time Awake Since Boot: 300000 seconds
Time Since Wake:       12000 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
dyld: launch, loading dependent libraries
DYLD_FALLBACK_LIBRARY_PATH=/Applications/CrossOver.app/Contents/SharedSupport/X11/lib:/Users/T1000/lib:/lib:/usr/lib:/usr/X11/lib

Dyld Error Message:
  Library not loaded: @executable_path/../lib/libquartz-wm-ds.1.dylib
  Referenced from: /Applications/CrossOver.app/Contents/SharedSupport/X11/bin/quartz-wm
  Reason: no suitable image found.  Did find:
	/Applications/CrossOver.app/Contents/SharedSupport/X11/bin/../lib/libquartz-wm-ds.1.dylib: mach-o, but wrong architecture
	/Applications/CrossOver.app/Contents/SharedSupport/X11/bin/../lib/libquartz-wm-ds.1.dylib: mach-o, but wrong architecture
	/Applications/CrossOver.app/Contents/SharedSupport/X11/lib/libquartz-wm-ds.1.dylib: mach-o, but wrong architecture

Binary Images:
0x8feef000 - 0x8ff235cf  dyld (360.18) <25D51D2B-794C-3911-9EEE-B1F0035D7104> /usr/lib/dyld
0x91be5000 - 0x928c0ffb  com.apple.AppKit (6.9 - 1404.34) <5DD0D072-B829-3ECC-AB5E-AF07CB2C85AB> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit

**Comment by IngmarStein** [comment]
Ok, this one is even trickier than #67. Here, libs and executables are both contained in the SharedSupport directory of a single bundle. I'll just add com.codeweavers.CrossOver to the blacklist.
Thanks for reporting!
