### ISSUE TITLE
don't dump massive dictionaries in syslog

### ISSUE THREAD

**Issue by tolgraven** [IngmarStein/Monolingual#69]
Where are your manners?

Awesome app tho.

**Comment by IngmarStein** [comment]
Which one? Starting with "Received request: "?

**Comment by tolgraven** [comment]
Well honestly basically all of it, I guess. The dictionary of blacklisted apps/files from the helper as well as all those apps then being repeated individually by the program itself. Feels dump to nitpick for a program that would get run so rarely, but several thousand lines of stuff that isn't relevant to the computer where it's currently being run just feels like noise for no good reason
Log the stuff actually on the system that has been spared thanks to the blacklist (the "excludes" part of the dict or the adding root / excluding root later), keep the rest internal :)

cheers!

net.sourceforge.MonolingualHelper[63557]: Received event in helper
net.sourceforge.MonolingualHelper[63557]: received message from peer(63399)

**Comment by IngmarStein** [comment]
Which version are you using? "net.sourceforge" indicates that it's an old version - newer ones have a "com.github.IngmarStein" prefix and don't spam the syslog.

**Comment by tolgraven** [comment]
Ah, fair play sorry, didn't realize you branch off on new OS X releases. Got a 5960X so still on 10.10...

**Comment by IngmarStein** [comment]
Alright. Closing this as I won't do another release in the old branch.
