### ISSUE TITLE
cause Xcode 7.2 Compile Error

### ISSUE THREAD

**Issue by wgywgy** [IngmarStein/Monolingual#70]
After run the applicaiton, Cause Xcode 7.2 comile Error When use coreData

**Comment by IngmarStein** [comment]
I'm not sure if I understand your question. Are you saying that you face compilation errors with Xcode that only occur after running Monolingual? In that very unlikely case, you should provide the actual error message, otherwise I'm unable to help.

**Comment by IngmarStein** [comment]
Closed because due to lack of feedback. Please reopen if you want to provide more detail.
