### ISSUE TITLE
Keeping a language localization from a previous OS

### ISSUE THREAD

**Issue by Rui-Valente** [IngmarStein/Monolingual#71]
Dear Mr. Stein,
I've only two languages in the Language&Region control Panel: Portuguese (Portugal) and English. In the new Mac OS version (10.11) the Portuguese (Portugal) language has changed. Previous OSes used the 1945 Orthographic Agreement but El Capitan is now following the 1990 Orthographic Agreement — which I hate. Is there a way to upgrade from 10.10 to 10.11 but leaving the old Portuguese (Portugal) file untouched?
Another option would be to create a new Portuguese (Portugal AO45) localization file. This would be the right thing to do since there are millions of users in the world (except Brazil) that still use the AO45. There's even Portuguese speaking countries like Angola and Mozambique that still use the AO45 as its official language.
I understand this is hardly a Monolingual related question, but I have googled this extensively in the web with no luck. Given all your knowledge on this subject maybe you could at least give me a hint about a place to search.
Thank you.
Rui

**Comment by IngmarStein** [comment]
Sorry, I don't think I can help here :/
