### ISSUE TITLE
Ignore Xcode libraries, et all?

### ISSUE THREAD

**Issue by maurymarkowitz** [IngmarStein/Monolingual#72]
I know this isn't a Q&A area, but it seems like the only place to ask... when I ran ML I noticed it was removing architectures from Xcode files. Is this OK? It would seem removing ARM code from a UB that works on iOS and MacOS might be a problem, but since I only develop (currently) on MacOS it seems to be working ok.

**Comment by IngmarStein** [comment]
Let me know if you encounter any problems. I haven't noticed any issues while building iOS apps for the simulator and devices.
