### ISSUE TITLE
Languages tab: sort by "Remove"

### ISSUE THREAD

**Issue by marconilanna** [IngmarStein/Monolingual#73]
It used to be that, under the "Languages" tab, we could click the "Remove" header to sort the list of languages by the status (checked/unchecked) of the checkboxes. That feature is quite useful because it allows us, at a quick glance, to double check that the list of languages that are not marked for removal is what we expect it to be.

**Comment by IngmarStein** [comment]
Thanks for spotting that! That was a regression from a previous version - the feature was lost during the transition to storyboards. I've re-added it and it will return in the next version.
