### ISSUE TITLE
Last version for Yosemite 10.10.5 is 1.7.1? (Site says 1.6.7)

### ISSUE THREAD

**Issue by bfranc1s** [IngmarStein/Monolingual#77]
I have Yosemite 10.10.5 and Monolingual 1.7.1.  It runs and works without problems - at least I have not noticed anything!  The web site says 1.6.7 is the last version for Yosemite.  Is there any reason not to run 1.7.1?  The issue doesn't come up for 1.7.3 because the app will not open.

**Comment by IngmarStein** [comment]
If you run 1.7.1 on Yosemite, you can continue to do so.

Officially, 1.6.7 is the last version for that OS because 1.7.x has an installation issue on Yosemite which Apple fixed in El Capitan (see #45). If you've successfully installed it, it should work just fine.

**Comment by bfranc1s** [comment]
Thanks for your quick response. I had no issues installing 1.7.1 so I will stay with it.  In the event that I need to reinstall it I am not sure I saved the original download.  All things being equal I would like the option of downloading the 1.7.1 version, with the understanding of course that there would be no support for using it with Yosemite.
