### ISSUE TITLE
Check for updates upon startup not working

### ISSUE THREAD

**Issue by Eitot** [IngmarStein/Monolingual#78]
I noticed that when I checked automatic updates in Sparkle’s prompt, the option in the preferences window remained unchecked. There are two separate keys for Sparkle updates in Monolingual’s defaults: `SUCheckAtStartup` (set by preferences) and `SUEnableAutomaticChecks` (set by Sparkle). I cannot find any reference to `SUEnableAutomaticChecks` in your source code and [only one](https://github.com/IngmarStein/Monolingual/blob/993aa02161a17ab01f36b2ecae4497add9582e2a/Resources/Base.lproj/Main.storyboard#L585) for `SUCheckAtStartup`.

When `SUEnableAutomaticChecks` is set to false and `SUCheckAtStartup` to true, nothing will actually happen when running an older version of Monolingual (I tested 1.7.2).

I had a look at the Sparkle source code and a search for `SUCheckAtStartup` only brought up [one result](https://github.com/sparkle-project/Sparkle/blob/0d52e27968f4896f49916767ccaba6fa24cabbe5/Sparkle/SUConstants.m#L41) for an unused variable `SUEnableAutomaticChecksKeyOld` (the last reference to this variable was removed in [this commit](https://github.com/sparkle-project/Sparkle/commit/c2672cf89ca8fa8327e8f1a30f170354f13d885a?diff=unified#diff-ed0e176891bb32f61956fa411b2a6be8L162)). I think that `SUCheckAtStartup` is obsolete.

I was thinking of a quick PR to replace the defaults key with `SUEnableAutomaticChecks`, but this will not actually check upon startup all the time by default.

**Comment by IngmarStein** [comment]
You're right, `SUCheckAtStartup` has been replaced by `SUEnableAutomaticChecks`, I'll update ML's storyboard accordingly. That option had been off by default in the past for privacy reasons, but now that ML updates the blacklist in the background and reports crashes with Fabric, I might make that opt-out instead.

**Comment by IngmarStein** [comment]
Fixed
