### ISSUE TITLE
Why won't MONOLINGUAL remove 2 letter .lproj languages?

### ISSUE THREAD

**Issue by kinku2002** [IngmarStein/Monolingual#8]
Since Tiger, Ive had to manually remove all "2 letter" languages by hand (except en.lproj) 

After I'm done, when i use EASYFIND, i eventually find only "english.lproj-and en.lproj" files left on my HD….BUT it IS such a pain is the arse to do.  

 *****I've never had any problems and have been removing them, for years.*****

also why not a  LOCK on both english.lproj and en.lproj so they are not accidentally deleted?

meaning you have to purposely unlock them to delete them. no more accidental deletions….

why won't monolingual remove these xx.lproj files?

**Comment by IngmarStein** [comment]
No feedback: closing issue. Please reopen if you still consider this to be in issue.
