### ISSUE TITLE
how to uninstall monolingual completely?

### ISSUE THREAD

**Issue by GHT52** [IngmarStein/Monolingual#83]
Hi,

I am now running Yosemite 10.10.5 on a Retina MacBook Pro and I have tried upgrading the system to El Capitan already 4 times. At each try, the system becomes highly unstable and so I have to revert to Yosemite using Time Machine. 
I asked for help on Apple site and Linc Davis, who is apparently a mac wizard, told me that Monolingual might be responsible for these problems.
Thus I would like to (hopefully temporarily) uninstall Monolingual completely for my machine. 
I now have Monolingual 1.7.1 installed (note that when I check for updates, it does not propose 1.7.3).
Could you tell me how to do this?
Many thanks for your help.
Gérald

**Comment by IngmarStein** [comment]
Monolingual does not have any components that affect the system when it is not running, so I cannot think of any way how uninstalling it could improve stability. Anyways, in addition to deleting the Monolingual application itself, here's a script to remove the helper: https://github.com/IngmarStein/Monolingual/blob/master/util/uninstall.sh

**Comment by GHT52** [comment]
Many thanks indeed.
In the case I continue using Monolingual with Yosemite (as I have been for
many years) should I download 1.7.3?
Kindest regards,

Gérald

............................................................................
..................................

Gérald Tenenbaum

Professeur

Institut Élie Cartan

Université de Lorraine

BP 70239

54506 Vand¦uvre lès Nancy Cedex

France



Téléphone : +33(0) 383 68 46 02

Télécopie : +33(0) 383 68 45 96

Mobile: +33 (0)6 20 89 28 25

Courriel: gerald.tenenbaum@univ-lorraine.fr

............................................................................
..................................



De :  Ingmar Stein <notifications@github.com>
Répondre à :  IngmarStein/Monolingual
<reply+00aff0af65fd59ee863933778fca9cfe52b42974b0872ec092cf00000001131b2ae99
2a169ce08b16173@reply.github.com>
Date :  mardi 5 avril 2016 09:27
À :  IngmarStein/Monolingual <Monolingual@noreply.github.com>
Cc :  Gérald Tenenbaum <gerald.ten@free.fr>
Objet :  Re: [IngmarStein/Monolingual] how to uninstall monolingual
completely? (#83)

**Comment by IngmarStein** [comment]
1.7.3 requires El Capitan, which is why it is not offered as an automatic upgrade.

**Comment by GHT52** [comment]
De :  Ingmar Stein <notifications@github.com>
Répondre à :  IngmarStein/Monolingual
<reply+00aff0af65fd59ee863933778fca9cfe52b42974b0872ec092cf00000001131b2ae99
2a169ce08b16173@reply.github.com>
Date :  mardi 5 avril 2016 09:27
À :  IngmarStein/Monolingual <Monolingual@noreply.github.com>
Cc :  Gérald Tenenbaum <gerald.ten@free.fr>
Objet :  Re: [IngmarStein/Monolingual] how to uninstall monolingual
completely? (#83)

> 
> Monolingual does not have any components that affect the system when it is not
> running, so I cannot think of any way how uninstalling it could improve
> stability. Anyways, in addition to deleting the Monolingual application
> itself, here's a script to remove the helper:
> https://github.com/IngmarStein/Monolingual/blob/master/util/uninstall.sh
> 
> 
Sorry, but how do I run this script?
I tried to open it with Xcode but this does not seem the right way. And
Script Editor does not help either.
Regards,

Gérald
>

**Comment by IngmarStein** [comment]
It's a shell script. You download it and execute it in Terminal. You can do it in one go by pasting the following line:
```
curl -s -O https://raw.githubusercontent.com/IngmarStein/Monolingual/master/util/uninstall.sh && chmod u+x uninstall.sh && ./uninstall.sh
```

**Comment by GHT52** [comment]
De :  Ingmar Stein <notifications@github.com>
Répondre à :  IngmarStein/Monolingual
<reply+00aff0afc183856dd185ee12f2b2a7b11ec80cc78d04023e92cf00000001131b78059
2a169ce08b16173@reply.github.com>
Date :  mardi 5 avril 2016 14:56
À :  IngmarStein/Monolingual <Monolingual@noreply.github.com>
Cc :  Gérald Tenenbaum <gerald.ten@free.fr>
Objet :  Re: [IngmarStein/Monolingual] how to uninstall monolingual
completely? (#83)

> 
> It's a shell script. You download it and execute it in Terminal. You can do it
> in one go by pasting the following line:
> curl -s -O 
> https://raw.githubusercontent.com/IngmarStein/Monolingual/master/util/uninstal
> l.sh && chmod u+x uninstall.sh && ./uninstall.sh
> 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/IngmarStein/Monolingual/issues/83#issuecomment-205789794>
> 
>   

Many thanks indeed.
Regards,

Gérald
