### ISSUE TITLE
PreferencesVC: roots.remove() does not work with Swift 3

### ISSUE THREAD

**Issue by Eitot** [IngmarStein/Monolingual#85]
This line does not seem to work anymore with Swift 3. The compiler infers `roots.remove(sender)` as `NSArrayController.remove(object:)` instead of `NSArrayController.remove(sender:)` as it does with Swift 2. Changing the passed value from `sender` to the `roots` instance of NSArrayController seems to solve the problem, but explicitly declaring the first parameter to enforce this (e.g. `roots.remove(sender: sender)`) does not seem to work. I have not looked into Swift 3 yet, but maybe you have an idea.

https://github.com/IngmarStein/Monolingual/blob/7da4c515121477bd290a8633366eeee815f6f1e3/Sources/PreferencesViewController.swift#L47

**Comment by IngmarStein** [comment]
Good find. I think that overload is unintentional and probably just temporary. I've added an explicit cast to work around the current situation.

**Comment by IngmarStein** [comment]
This is tracked as https://bugs.swift.org/browse/SR-1476
