### ISSUE TITLE
Suggestion: GUI appears unresponsive while searching

### ISSUE THREAD

**Issue by SundialServices** [IngmarStein/Monolingual#86]
On second and subsequent runs of the product, the user interface appears to be unresponsive because the messages aren't being updated.  This appears to happen when the product is, in fact, "looking" for another entry that needs cleaning.

I would therefore suggest that some kind of "twirler" be added, and/or that a timer be used to notice when the on-screen message hasn't changed in a while.  Let the message change to something like "Searching ." ... "Searching .." ... "Searching ..." just so that it's clear that something is actually going on at all times.  

I don't think that a "progress bar" is entirely practical but that also might be worth considering, even if it only updates (say) at a per-Application level.

**Comment by IngmarStein** [comment]
Good suggestion. Will be part of the next release.

**Comment by lycan2k8** [comment]
I keep unsubscribing to this list and the emails keep coming! FFS!!
