### ISSUE TITLE
Improvement: add tab for FONT files for languages not used

### ISSUE THREAD

**Issue by DG12** [IngmarStein/Monolingual#89]
3MB FONT files (of which there are 41)
sudo /usr/bin/find /Library/Fonts -size +4M -ls

AppleMyungjo.ttf, Baoli.ttc, Gungseouche.ttf, Hannotate.ttc, Hanzipen.ttc, Kaiti.ttc, Klee.ttc, Lantinghei.ttc, Libian.ttc, NanumGothic.ttc, NanumMyeongjo.ttc, NanumScript.ttc, NISC18030.ttf, PCmyoungjo.ttf, Songti.ttc, TsukushiAMaruGothic.ttc, TsukushiBMaruGothic.ttc, WawaSC-Regular.otf, WawaTC-Regular.otf, WeibeiSC-Bold.otf, WeibeiTC-Bold.otf, Xingkai.ttc, Yu Gothic Bold.otf, Yu Gothic Medium.otf, Yuanti.ttc, YuMincho.ttc, YuppyTC-Regular.otf,YuppySC-Regular.otf,
ヒラギノ丸ゴ ProN W4.ttc, 儷宋 Pro.ttf ,儷黑 Pro.ttf , 华文仿宋.ttf , 华文细黑.ttf, 华文黑体.ttf

include size in list to permit sorting by size.

Dynamically generated of course.
Maybe not AppleGothic.ttf or Arial Unicode.ttf

Thank you

**Comment by Eitot** [comment]
Font Book shows that most if not all of these fonts have languages associated with them. It should be possible to select the fonts based on this. I am not sure if it is possible to verify this at runtime, I don’t think Apple has public APIs to examine font files.

I only came across Apple’s font tools (`ftxdumperfuser` among others) on the developer site with which font data can be read. The `ltag` and `meta` tables of font files seem to be relevant, but I don’t think it is exhaustive (e.g. the language information for Baskerville is not recorded in these two tables).

For reference:
https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6ltag.html 
https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6meta.html

**Comment by IngmarStein** [comment]
Even if I find a way to get the list of languages supported by a specific font, I don't see how that can help determining which ones to delete. AppleMyungjo for example has the following list: "English, Indonesian, Korean, Cornish, Malay, Oromo, Somali, Swahili, Zulu". It supports the Latin script. Should that font remain on a English-only system?

I'm not sure if the potential savings are worth the trouble.

**Comment by Eitot** [comment]
Sierra also seems to delete/not download some of these fonts now as part of Optimized Storage. You have to download some of them separately now.

**Comment by DG12** [comment]
Thanks for you consideration.

**Comment by bumper314** [comment]
As a resource for anyone interested in removing fonts, here's a pretty exhaustive writeup: http://www.jklstudios.com/misc/osxfonts.html#requiredfonts
