### ISSUE TITLE
Sierra German language packs for some programs gone

### ISSUE THREAD

**Issue by Thomasmac** [IngmarStein/Monolingual#92]
Hi, just updated to Sierra. As usual I had a monolingual run. Settings as always. While the program was running I wondered why some German language packages had been erased. A few days later I notices that Evernote, iTunes, Pages, Numbers and Keynote were available in English only. A few other programs as well. I deinstalled and re-installed them. Core-Programs like Preview or Finder, however, stayed German. I guess that Monolingual is not yet compatible with Sierra. Any fix in sight?

**Comment by Thomasmac** [comment]
Found out the reason why this happened. After Update to Sierra the previously chosen settings have been ignored. I always keep German as this is my native language. After opening monolingual the previously chosen language to keep (no tick) was "Deutsch". After upgrade to Sierra the "blanc" was moved to "Deutsch (Deutschland)". "Deutsch", however", was ticked to be removed. As a result core programs kept "Deutsch" and most of the other programs lost German. Whenever I re-open monolingual "Deutsch" is ticked (although I deselected it). No doubt that this has to be fixed. Now I know about this behavior. Before I trusted in Monolingual keeping settings - a mistake!
![screenshot_323](https://cloud.githubusercontent.com/assets/7227042/19408702/b2b64cdc-92bb-11e6-8761-c4dcd42342c4.jpg)

**Comment by DotTheI** [comment]
I am experiencing the same issue on Sierra. Every time I start Monolingual, I found my system language selected for removal and have to manually uncheck it. A dozen applications had their localizations removed before I noticed that.

**Comment by IngmarStein** [comment]
Thanks for the report. Seems like Sierra changed the way it reports the user's locale. Will be fixed in the next version.

**Comment by tsis2k** [comment]
hello all
my problem is with the Spanish language, now office 2016 applications, chrome etc ... appear only in English and the native operating system in Spanish. 
I can solve this problem?

**Comment by IngmarStein** [comment]
This should be fixed in 1.7.4. Could you please verify?

**Comment by DotTheI** [comment]
Confirm. Thank you!
