### ISSUE TITLE
Monolingual 1.7.3 removes Japanese.lproj on macOS 10.12 Sierra

### ISSUE THREAD

**Issue by suishouen** [IngmarStein/Monolingual#93]
I set Preferred languages: English - Primary and Japanese - Secondary in System Preferences > Language & Region.

Monolingual always checks Japanese (Select the items you wish to remove), so it removes Japanese.lproj.
I uncheck Japanese, but that settings cannot be saved.

See screenshot:
![screen shot 2016-10-28 at 21 20 29](https://cloud.githubusercontent.com/assets/21173308/19806378/658d6e6e-9d55-11e6-8013-9da96a913b16.png)

Best Regards.

**Comment by IngmarStein** [comment]
Same as #92?

**Comment by suishouen** [comment]
> Same as #92?

If the issue of #92 is stated as:

"Since Sierra changed the way it reports the user's locale, Monolingual should follow that", 

then "Yes".

**Comment by suishouen** [comment]
I think that **"Monolingual 1.7.3 is not compatible with macOS 10.12 Sierra"** is noted in the release notes till this issue will be fixed.

**Comment by IngmarStein** [comment]
Should be fixed in 1.7.4
