### ISSUE TITLE
change languages other applications 

### ISSUE THREAD

**Issue by tsis2k** [IngmarStein/Monolingual#94]
hello all
my problem is with the Spanish language, now office 2016 applications, chrome etc ... appear only in English and the native operating system in Spanish. 
I can solve this problem?

**Comment by Eitot** [comment]
Related to #92 and #93. There is a bug in Monolingual that prevents automatic deselection of the ‘base’ languages, i.e. es, de, fr. I’m afraid you have deleted those languages and the only way to get them back is by reinstalling the applications in question. If the system as a whole is affected, then you have to roll back or reinstall Sierra.

**Comment by IngmarStein** [comment]
Should be fixed in 1.7.4
