### ISSUE TITLE
Get some languages back

### ISSUE THREAD

**Issue by VijendraMalhotra** [IngmarStein/Monolingual#95]
Hi,
I need to get some languages back that were deleted by Monolingual's earlier Sierra bugs. I have tried to reinstall the apps (like chrome) but I still get boxes instead of the actual text in chrome. 
Is there anyway to test if the issue is with the general system of just chrome? If its indeed with Chrome how can i get chrome to start displaying those languages back again?

**Comment by Eitot** [comment]
It is probably prudent to just reinstall the system from Recovery. It won’t delete any of your files, just repair the system.

**Comment by VijendraMalhotra** [comment]
Done that no change 



Vijendra Malhotra 

- Sent from my iP*

**Comment by IngmarStein** [comment]
Were you able to diagnose the problem?

**Comment by IngmarStein** [comment]
Closed due to lack of feedback.
