### ISSUE TITLE
Word+Excel+Powerpoint destroyed, Adobe Illustrator destroyed, system unstable.

### ISSUE THREAD

**Issue by Ripalda** [IngmarStein/Monolingual#96]
After running Monolingual with default settings (Remove all architectures but current Intel 64)

Sample crash report from Word.

Process:               Microsoft Word [9132]
Path:                  /Applications/Microsoft Office 2011/Microsoft Word.app/Contents/MacOS/Microsoft Word
Identifier:            com.microsoft.Word
Version:               ???
Build Info:            Unknown-141117~0
Code Type:             X86 (Native)
Parent Process:        ??? [1]
Responsible:           Microsoft Word [9132]
User ID:               501

Date/Time:             2016-11-15 17:46:13.258 +0100
OS Version:            Mac OS X 10.11.6 (15G31)
Report Version:        11
Anonymous UUID:        CE85872E-3A6D-D2BA-A974-450F1AE7A001

Sleep/Wake UUID:       D656D3FA-61BA-40BD-B5DA-85DEDD97EC32

Time Awake Since Boot: 450000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/mbuinstrument.framework/Versions/14/mbuinstrument
  Referenced from: /Applications/Microsoft Office 2011/Microsoft Word.app/Contents/MacOS/Microsoft Word
  Reason: no suitable image found.  Did find:
	/Applications/Microsoft Office 2011/Microsoft Word.app/Contents/MacOS/../../../Office/mbuinstrument.framework/Versions/14/mbuinstrument: mach-o, but wrong architecture

Binary Images:
0x8fe66000 - 0x8fe9adf7  dyld (360.22) <16F74106-838E-37A2-82C3-6B382F52101C> /usr/lib/dyld
0x94af6000 - 0x94af6fff  com.apple.Cocoa (6.11 - 22) <5DE99658-0C2F-3DB0-8741-B9D36FCF04D8> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
0x94d78000 - 0x94d78fff  com.apple.Carbon (154 - 157) <25DB41AD-B46F-3FC2-8FFB-325750777CC0> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
0x98ce6000 - 0x98ec8fff  com.apple.QuartzCore (1.11 - 410.14) <F4525113-0692-362E-B3BA-1C5A2950CA4C> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
0x9a7fe000 - 0x9aa7cfef  com.apple.QuickTime (7.7.3 - 2943.12) <625E17BC-E584-3903-AA10-D0876CE36CCB> /System/Library/Frameworks/QuickTime.framework/Versions/A/QuickTime

Model: Macmini5,2, BootROM MM51.0077.B14, 2 processors, Intel Core i5, 2,5 GHz, 4 GB, SMC 1.75f0
Graphics: AMD Radeon HD 6630M, AMD Radeon HD 6630M, PCIe, 256 MB
Memory Module: BANK 0/DIMM0, 2 GB, DDR3, 1333 MHz, 0x80AD, 0x484D54333235533642465238432D48392020
Memory Module: BANK 1/DIMM0, 2 GB, DDR3, 1333 MHz, 0x80AD, 0x484D54333235533642465238432D48392020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0xE4), Broadcom BCM43xx 1.0 (5.106.98.100.24)
Bluetooth: Version 4.4.6f1 17910, 3 services, 18 devices, 1 incoming serial ports
Network Service: Ethernet, Ethernet, en0
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: OCZ-VERTEX3, 60,02 GB
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: External USB 3.0
USB Device: USB Keyboard
USB Device: IR Receiver
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: USB Trackball
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: Mac mini, Apple Inc., 22.2

**Comment by IngmarStein** [comment]
The underlying issue should have been fixed in 1.7.4.

**Comment by IngmarStein** [comment]
Closed due to lack of feedback. Please reopen if this is still an issue with the current release.
