### ISSUE TITLE
Monolingual 1.7.4 crashes, when I open preferences and add directories to remove.

### ISSUE THREAD

**Issue by suishouen** [IngmarStein/Monolingual#97]
Monolingual 1.7.4 crashes, when I open preferences and add directories to remove.
Platform: macOS Sierra Version 10.12.2 (16C67)
---
com.apple.message.domain: com.apple.crashreporter.writereport.crash
com.apple.message.signature: Monolingual
com.apple.message.signature2: com.github.IngmarStein.Monolingual ||| 1.7.4 (1.7.4)
com.apple.message.signature3: UNKNOWN
com.apple.message.result: YES
com.apple.message.summarize: YES
SenderMachUUID: E09A71B1-7DB9-3F89-8E54-164DE703B561

**Comment by IngmarStein** [comment]
Oops. I can reproduce the issue and will try to fix it. Thanks for the report.

**Comment by IngmarStein** [comment]
This will be fixed in 1.7.5. I'll wait some time if anything else pops up which should go into the next release.

**Comment by hatoncat** [comment]
Can we get a v1.7.4.1 release for those of us stuck on El Capitan? The app crashes the moment I fire up Preferences. Between this, and the Helper tool bug, Monolingual now runs on zero of my Macs. :(

**Comment by IngmarStein** [comment]
Oh, I didn't realize that not all Macs can be upgraded to Sierra…

I can at least offer a Terminal-based workaround to add items to the list of root folders:
```
defaults write ~/Library/Containers/com.github.IngmarStein.Monolingual/Data/Library/Preferences/com.github.IngmarStein.Monolingual.plist Roots -array-add '{ "Architectures" = 1; "Languages" = "1"; "Path" = "<your path here>";}'
```

**Comment by IngmarStein** [comment]
Oh, I didn't realize that not all Macs can be updated from 10.11 to Sierra…

At least, I can offer a Terminal-based workaround to add items to the directory list:
```
defaults write ~/Library/Containers/com.github.IngmarStein.Monolingual/Data/Library/Preferences/com.github.IngmarStein.Monolingual.plist Roots -array-add '{ "Architectures" = 1; "Languages" = "1"; "Path" = "<your path here>";}'
```
