### ISSUE TITLE
macOS 10.12 required since 1.7.4

### ISSUE THREAD

**Issue by chohner** [IngmarStein/Monolingual#99]
Since monolingual 1.7.4, macOS 10.12 is required to start the app. Is this on purpose? 1.7.3 is working fine on 10.11.6

**Comment by IngmarStein** [comment]
Yes, this is intended and documented on https://ingmarstein.github.io/Monolingual/. 1.7.4 uses some APIs introduced in Sierra.

**Comment by chohner** [comment]
Thanks for the fast response, my bad!
